In [1]:
import os

print(os.listdir("."))

['.ipynb_checkpoints', 'ADB_port_traffic_data.csv', 'era5_hourly_test', 'era5_hourly_test.zip', 'era5_multi_point_test', 'era5_multi_point_test.zip', 'era5_test', 'era5_test.zip', 'era5_test_cell_1', 'era5_test_cell_1.zip', 'era5_test_cell_2.zip', 'era5_test_cell_3.zip', 'era5_test_cell_4.zip', 'era5_test_cell_5.zip', 'era5_tile_40_0_2024_01_01.csv', 'era5_tile_test', 'era5_tile_test.zip', 'era5_tile_test_2', 'era5_tile_test_2.zip', 'global_weather_locations.csv', 'ports_master.csv', 'test_era5.py', 'Weather_Forecasting_Model.ipynb', 'WPI_2026.csv', 'WPI_Port_Data_Analysis.ipynb']

In [2]:
import pandas as pd

ports = pd.read_csv("ports_master.csv")

print("Shape:", ports.shape)
print("\nColumns:")
print(ports.columns.tolist())

print("\nFirst 5 rows:")
display(ports[[
    "Main Port Name",
    "UN/LOCODE",
    "Latitude",
    "Longitude"
]].head())

Shape: (3807, 35)

Columns:
['World Port Index Number', 'Region Name', 'Main Port Name', 'Alternate Port Name', 'UN/LOCODE', 'Country Code', 'World Water Body', 'IHO S-130 Sea Area', 'Latitude', 'Longitude', 'Tidal Range (m)', 'Entrance Width (m)', 'Channel Depth (m)', 'Anchorage Depth (m)', 'Cargo Pier Depth (m)', 'Maximum Vessel Length (m)', 'Maximum Vessel Beam (m)', 'Maximum Vessel Draft (m)', 'Harbor Size', 'Harbor Type', 'Harbor Use', 'Shelter Afforded', 'Entrance Restriction - Tide', 'Entrance Restriction - Heavy Swell', 'Entrance Restriction - Ice', 'Entrance Restriction - Other', 'Overhead Limits', 'Underkeel Clearance Management System', 'Good Holding Ground', 'Turning Area', 'Port Security', 'Traffic Separation Scheme', 'Vessel Traffic Service', 'Pilotage - Compulsory', 'Pilotage - Available']

First 5 rows:

      Main Port Name UN/LOCODE   Latitude  Longitude
0             Maurer            40.533333 -74.250000
1            Iharana           -13.350000  50.000000
2        Chake Chake            -5.250000  39.766667
3  Mjimwema Terminal            -6.816667  39.366667
4     Delta Terminal            36.850000  36.166667

In [3]:
print("Number of unique countries:", ports["Country Code"].nunique())

print("\nTop 20 countries by number of ports:")
print(
    ports["Country Code"]
    .value_counts()
    .head(20)
)

Number of unique countries: 195

Top 20 countries by number of ports:
Country Code
United States     666
Canada            285
United Kingdom    186
Japan             163
Norway            141
Italy             123
Indonesia         123
Sweden             92
Philippines        71
Denmark            69
Russia             68
Australia          66
France             66
China              66
Greece             57
India              55
Turkey             54
Spain              52
Brazil             45
Iceland            43
Name: count, dtype: int64

In [4]:
import pandas as pd

adb = pd.read_csv("ADB_port_traffic_data.csv")

adb.columns = adb.columns.str.strip()

print("ADB shape:", adb.shape)

print("\nUnique ports:")
print(adb["Port"].unique())

print("\nNumber of unique ports:", adb["Port"].nunique())

ADB shape: (3991, 70)

Unique ports:
['Antwerp' 'Busan' 'Dubai' 'Guangzhou' 'Hamburg' 'Hong Kong' 'Kaohsiung'
 'LALB' 'NYNJ' 'Ningbo' 'Port Klang' 'Qingdao' 'Rotterdam' 'Shanghai'
 'Shenzhen' 'Singapore' 'Tanjung Pelepas' 'Tianjin' 'Xiamen' nan]

Number of unique ports: 19

In [5]:
import pandas as pd

ports = pd.read_csv("ports_master.csv")

print("Total ports:", len(ports))

print("Missing latitude:", ports["Latitude"].isna().sum())
print("Missing longitude:", ports["Longitude"].isna().sum())

print("\nLatitude range:")
print(ports["Latitude"].min(), "to", ports["Latitude"].max())

print("\nLongitude range:")
print(ports["Longitude"].min(), "to", ports["Longitude"].max())

Total ports: 3807
Missing latitude: 0
Missing longitude: 0

Latitude range:
-77.84999999999998 to 78.928333333

Longitude range:
-177.366667 to 179.3675

In [6]:
# Check for duplicate coordinates
duplicate_coordinates = (
    ports.groupby(["Latitude", "Longitude"])
    .size()
    .reset_index(name="count")
)

duplicate_coordinates = duplicate_coordinates[
    duplicate_coordinates["count"] > 1
]

print("Duplicate coordinate locations:", len(duplicate_coordinates))

if len(duplicate_coordinates) > 0:
    display(duplicate_coordinates.head(20))

Duplicate coordinate locations: 11

       Latitude   Longitude  count
1578  34.700000  134.833333      2
1943  39.950000  -75.133333      2
1974  40.550000  -74.250000      2
1980  40.633333  -74.200000      2
1982  40.633333  -74.066667      2
2195  42.616667  -82.516667      2
2199  42.650000  -73.750000      2
2349  43.966667 -124.116667      2
2525  45.433333  -75.700000      2
2924  51.433333    0.700000      2
3426  59.233333 -135.433333      2

In [7]:
# Create unique weather locations from the global port database

weather_locations = (
    ports[
        [
            "World Port Index Number",
            "Main Port Name",
            "UN/LOCODE",
            "Country Code",
            "Latitude",
            "Longitude"
        ]
    ]
    .drop_duplicates(subset=["Latitude", "Longitude"])
    .reset_index(drop=True)
)

print("Total WPI ports:", len(ports))
print("Unique weather locations:", len(weather_locations))

display(weather_locations.head(10))

Total WPI ports: 3807
Unique weather locations: 3796

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude
0,7950.0,Maurer,,United States,40.533333,-74.250000
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000
7,7010.0,New Harbor,,United States,43.866667,-69.483333
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000

In [8]:
weather_locations = (
    ports[
        [
            "World Port Index Number",
            "Main Port Name",
            "UN/LOCODE",
            "Country Code",
            "Latitude",
            "Longitude"
        ]
    ]
    .drop_duplicates(subset=["Latitude", "Longitude"])
    .reset_index(drop=True)
)

print("Total WPI ports:", len(ports))
print("Unique weather locations:", len(weather_locations))

display(weather_locations.head(10))

Total WPI ports: 3807
Unique weather locations: 3796

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude
0,7950.0,Maurer,,United States,40.533333,-74.250000
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000
7,7010.0,New Harbor,,United States,43.866667,-69.483333
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000

In [9]:
# Save unique global weather locations

weather_locations.to_csv(
    "global_weather_locations.csv",
    index=False
)

print("Saved:", "global_weather_locations.csv")
print("Rows:", len(weather_locations))
print("Columns:", list(weather_locations.columns))

Saved: global_weather_locations.csv
Rows: 3796
Columns: ['World Port Index Number', 'Main Port Name', 'UN/LOCODE', 'Country Code', 'Latitude', 'Longitude']

In [10]:
# Map each port to its ERA5 atmospheric grid cell

weather_locations["era5_lat"] = (
    (weather_locations["Latitude"] * 4).round() / 4
)

weather_locations["era5_lon"] = (
    (weather_locations["Longitude"] * 4).round() / 4
)

unique_era5_cells = (
    weather_locations[
        ["era5_lat", "era5_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique weather locations:", len(weather_locations))
print("Unique ERA5 atmospheric grid cells:", len(unique_era5_cells))

display(unique_era5_cells.head(10))

Unique weather locations: 3796
Unique ERA5 atmospheric grid cells: 3124

   era5_lat  era5_lon
0     40.50    -74.25
1    -13.25     50.00
2     -5.25     39.75
3     -6.75     39.25
4     36.75     36.25
5     -5.50    106.25
6     36.25     -5.25
7     43.75    -69.50
8    -22.75    -43.25
9     28.00     35.25

In [11]:
# Map each port to the ERA5 ocean-wave grid

weather_locations["wave_lat"] = (
    (weather_locations["Latitude"] * 2).round() / 2
)

weather_locations["wave_lon"] = (
    (weather_locations["Longitude"] * 2).round() / 2
)

unique_wave_cells = (
    weather_locations[
        ["wave_lat", "wave_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique weather locations:", len(weather_locations))
print("Unique ERA5 atmospheric cells:", len(unique_era5_cells))
print("Unique ERA5 wave cells:", len(unique_wave_cells))

display(unique_wave_cells.head(10))

Unique weather locations: 3796
Unique ERA5 atmospheric cells: 3124
Unique ERA5 wave cells: 2581

   wave_lat  wave_lon
0      40.5     -74.0
1     -13.5      50.0
2      -5.0      40.0
3      -7.0      39.5
4      37.0      36.0
5      -5.5     106.0
6      36.0      -5.5
7      44.0     -69.5
8     -23.0     -43.0
9      28.0      35.0

In [12]:
print("Global weather locations:", len(weather_locations))

print(
    "Unique ERA5 atmospheric cells:",
    weather_locations[["era5_lat", "era5_lon"]]
    .drop_duplicates()
    .shape[0]
)

print(
    "Unique ERA5 wave cells:",
    weather_locations[["wave_lat", "wave_lon"]]
    .drop_duplicates()
    .shape[0]
)

weather_locations[
    [
        "Main Port Name",
        "UN/LOCODE",
        "Latitude",
        "Longitude",
        "era5_lat",
        "era5_lon",
        "wave_lat",
        "wave_lon"
    ]
].head(10)

Global weather locations: 3796
Unique ERA5 atmospheric cells: 3124
Unique ERA5 wave cells: 2581

,Main Port Name,UN/LOCODE,Latitude,Longitude,era5_lat,era5_lon,wave_lat,wave_lon
0,Maurer,,40.533333,-74.250000,40.50,-74.25,40.5,-74.0
1,Iharana,,-13.350000,50.000000,-13.25,50.00,-13.5,50.0
2,Chake Chake,,-5.250000,39.766667,-5.25,39.75,-5.0,40.0
3,Mjimwema Terminal,,-6.816667,39.366667,-6.75,39.25,-7.0,39.5
4,Delta Terminal,,36.850000,36.166667,36.75,36.25,37.0,36.0
5,Cinta Oil Terminal,,-5.500000,106.233333,-5.50,106.25,-5.5,106.0
6,Europa Point,,36.133333,-5.350000,36.25,-5.25,36.0,-5.5
7,New Harbor,,43.866667,-69.483333,43.75,-69.50,44.0,-69.5
8,Dtse / Gegua Oil Terminal,,-22.816667,-43.150000,-22.75,-43.25,-23.0,-43.0
9,Sharmah,,27.933333,35.250000,28.00,35.25,28.0,35.0

In [13]:
print("Shape:", weather_locations.shape)

print("\nColumns:")
print(weather_locations.columns.tolist())

print("\nFirst 10 locations:")
display(weather_locations.head(10))

print("\nUnique countries:", weather_locations["Country Code"].nunique())

print("\nUnique ERA5 cells:",
      weather_locations[["era5_lat", "era5_lon"]].drop_duplicates().shape[0])

print("\nUnique wave cells:",
      weather_locations[["wave_lat", "wave_lon"]].drop_duplicates().shape[0])

Shape: (3796, 10)

Columns:
['World Port Index Number', 'Main Port Name', 'UN/LOCODE', 'Country Code', 'Latitude', 'Longitude', 'era5_lat', 'era5_lon', 'wave_lat', 'wave_lon']

First 10 locations:

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude,era5_lat,era5_lon,wave_lat,wave_lon
0,7950.0,Maurer,,United States,40.533333,-74.250000,40.50,-74.25,40.5,-74.0
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000,-13.25,50.00,-13.5,50.0
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667,-5.25,39.75,-5.0,40.0
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667,-6.75,39.25,-7.0,39.5
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667,36.75,36.25,37.0,36.0
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333,-5.50,106.25,-5.5,106.0
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000,36.25,-5.25,36.0,-5.5
7,7010.0,New Harbor,,United States,43.866667,-69.483333,43.75,-69.50,44.0,-69.5
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000,-22.75,-43.25,-23.0,-43.0
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000,28.00,35.25,28.0,35.0

Unique countries: 195

Unique ERA5 cells: 3124

Unique wave cells: 2581

In [14]:
era5_cells = (
    weather_locations[
        ["era5_lat", "era5_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("ERA5 cells:", era5_cells.shape)

display(era5_cells.head(20))

ERA5 cells: (3124, 2)

    era5_lat  era5_lon
0      40.50    -74.25
1     -13.25     50.00
2      -5.25     39.75
3      -6.75     39.25
4      36.75     36.25
5      -5.50    106.25
6      36.25     -5.25
7      43.75    -69.50
8     -22.75    -43.25
9      28.00     35.25
10     29.75    -95.25
11     44.25    -68.50
12     43.75    -69.00
13     -8.00    -14.25
14      8.00    102.25
15     -0.75    119.75
16     38.50     23.25
17     37.50     -1.50
18     37.00     15.25
19     19.50     37.25

In [15]:
test_era5_cells = era5_cells.head(5)

display(test_era5_cells)

   era5_lat  era5_lon
0     40.50    -74.25
1    -13.25     50.00
2     -5.25     39.75
3     -6.75     39.25
4     36.75     36.25

In [16]:
import cdsapi

client = cdsapi.Client()

test_cells = test_era5_cells.values.tolist()

for i, (lat, lon) in enumerate(test_cells, start=1):

    print(f"Downloading cell {i}/5: {lat}, {lon}")

    client.retrieve(
        "reanalysis-era5-single-levels",
        {
            "product_type": "reanalysis",
            "variable": [
                "10m_u_component_of_wind",
                "10m_v_component_of_wind",
                "total_precipitation",
                "2m_temperature"
            ],
            "year": "2024",
            "month": "01",
            "day": "01",
            "time": [
                "00:00",
                "06:00",
                "12:00",
                "18:00"
            ],
            "area": [
                lat + 0.125,
                lon - 0.125,
                lat - 0.125,
                lon + 0.125
            ],
            "data_format": "netcdf",
            "download_format": "unarchived"
        },
        f"era5_test_cell_{i}.zip"
    )

print("All 5 ERA5 test downloads completed.")

2026-10-07 23:17:57,981 INFO [2026-10-06T00:00:00Z] The [CDS Terms of Use](https://cds.climate.copernicus.eu/disclaimer-privacy) will be updated on 28 October 2026. Continued use of Copernicus Products and Services through the CDS after this date constitutes acceptance of the updated terms. If you do not accept the change, please [contact ECMWF Support](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202) before 27 October 2026.
 **[More information about the upcoming change.](https://forum.ecmwf.int/t/upcoming-cds-terms-of-use-change/15374)**

Downloading cell 1/5: 40.5, -74.25

2026-10-07 23:17:59,268 INFO Request ID is 1473ccac-a215-4aa7-bbaa-0ec04788aff3
2026-10-07 23:18:01,320 INFO status has been updated to successful

73e44e53361db01b56393d0fe1712cb4.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 2/5: -13.25, 50.0

2026-10-07 23:18:06,155 INFO Request ID is ab7ee349-fbb2-4a63-bbf1-6b03f4d994e1
2026-10-07 23:18:06,539 INFO status has been updated to successful

27fd17361bb425b5955e6ef3225ae6.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 3/5: -5.25, 39.75

2026-10-07 23:18:11,479 INFO Request ID is 9a4e8bdc-e93d-4a5a-9ecf-afdffcc9106d
2026-10-07 23:18:11,779 INFO status has been updated to successful

a038be5109b2afecc128a65aeaa4350b.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 4/5: -6.75, 39.25

2026-10-07 23:18:16,185 INFO Request ID is 130f51f8-12ea-4384-a0fe-5d61cea25161
2026-10-07 23:18:19,148 INFO status has been updated to successful

1c96d60a1c481167f036cf71aa9c6e6a.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 5/5: 36.75, 36.25

2026-10-07 23:18:21,984 INFO Request ID is 0bfa5e8c-49ac-4316-94e4-55001cdbdecd
2026-10-07 23:18:22,231 INFO status has been updated to successful

5bd7257876d460b013958bd4be24684.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

All 5 ERA5 test downloads completed.

In [17]:
import os
import glob

files = glob.glob("era5_test_cell_*.zip")

print("Downloaded files:", len(files))

for file in files:
    size_kb = os.path.getsize(file) / 1024
    print(f"{file} → {size_kb:.2f} KB")

Downloaded files: 5
era5_test_cell_1.zip → 67.89 KB
era5_test_cell_2.zip → 67.89 KB
era5_test_cell_3.zip → 67.89 KB
era5_test_cell_4.zip → 67.89 KB
era5_test_cell_5.zip → 67.89 KB

In [18]:
import zipfile
import os

zip_file = "era5_test_cell_1.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

In [19]:
import zipfile
import xarray as xr

zip_file = "era5_test_cell_1.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall("era5_test_cell_1")

instant_file = "era5_test_cell_1/data_stream-oper_stepType-instant.nc"
accum_file = "era5_test_cell_1/data_stream-oper_stepType-accum.nc"

instant_ds = xr.open_dataset(instant_file, engine="netcdf4")
accum_ds = xr.open_dataset(accum_file, engine="netcdf4")

print("=== INSTANT DATA ===")
print(instant_ds)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds)

=== INSTANT DATA ===
<xarray.Dataset> Size: 168B
Dimensions:     (valid_time: 4, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 16B ...
    v10         (valid_time, latitude, longitude) float32 16B ...
    t2m         (valid_time, latitude, longitude) float32 16B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-25T16:45 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 136B
Dimensions:     (valid_time: 4, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 16B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-25T16:45 GRIB to CDM+CF via cfgrib-0.9.1...

In [20]:
import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00",
            "06:00",
            "12:00",
            "18:00"
        ],
        "area": [
            40.75,
            -74.50,
            40.25,
            -74.00
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_multi_point_test.zip"
)

print("Multi-point ERA5 download completed.")

2026-10-07 23:18:29,252 INFO [2026-10-06T00:00:00Z] The [CDS Terms of Use](https://cds.climate.copernicus.eu/disclaimer-privacy) will be updated on 28 October 2026. Continued use of Copernicus Products and Services through the CDS after this date constitutes acceptance of the updated terms. If you do not accept the change, please [contact ECMWF Support](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202) before 27 October 2026.
 **[More information about the upcoming change.](https://forum.ecmwf.int/t/upcoming-cds-terms-of-use-change/15374)**
2026-10-07 23:18:30,116 INFO Request ID is c7ae29f8-6e62-4ff7-a83b-5b9a9c383983
2026-10-07 23:18:30,350 INFO status has been updated to successful

8a15e5f0f0e9aa761edf76851d80ee8a.zip:   0%|          | 0.00/67.4k [00:00<?, ?B/s]

Multi-point ERA5 download completed.

In [21]:
import zipfile

zip_file = "era5_multi_point_test.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

In [22]:
import zipfile
import xarray as xr

zip_file = "era5_multi_point_test.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall("era5_multi_point_test")

instant_file = "era5_multi_point_test/data_stream-oper_stepType-instant.nc"
accum_file = "era5_multi_point_test/data_stream-oper_stepType-accum.nc"

instant_ds = xr.open_dataset(instant_file, engine="netcdf4")
accum_ds = xr.open_dataset(accum_file, engine="netcdf4")

print("=== INSTANT DATA ===")
print(instant_ds)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds)

=== INSTANT DATA ===
<xarray.Dataset> Size: 584B
Dimensions:     (valid_time: 4, latitude: 3, longitude: 3)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 24B 40.75 40.5 40.25
  * longitude   (longitude) float64 24B -74.5 -74.25 -74.0
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 144B ...
    v10         (valid_time, latitude, longitude) float32 144B ...
    t2m         (valid_time, latitude, longitude) float32 144B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 296B
Dimensions:     (valid_time: 4, latitude: 3, longitude: 3)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 24B 40.75 40.5 40.25
  * longitude   (longitude) float64 24B -74.5 -74.25 -74.0
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 144B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.1...

In [23]:
print("ERA5 latitude range:")
print("Minimum:", era5_cells["era5_lat"].min())
print("Maximum:", era5_cells["era5_lat"].max())

print("\nERA5 longitude range:")
print("Minimum:", era5_cells["era5_lon"].min())
print("Maximum:", era5_cells["era5_lon"].max())

print("\nTotal ERA5 cells:", len(era5_cells))

ERA5 latitude range:
Minimum: -77.75
Maximum: 79.0

ERA5 longitude range:
Minimum: -177.25
Maximum: 179.25

Total ERA5 cells: 3124

In [24]:
import numpy as np

era5_cells["lat_tile"] = (
    np.floor(era5_cells["era5_lat"] / 20) * 20
)

era5_cells["lon_tile"] = (
    np.floor(era5_cells["era5_lon"] / 20) * 20
)

tiles = (
    era5_cells[["lat_tile", "lon_tile"]]
    .drop_duplicates()
    .sort_values(["lat_tile", "lon_tile"])
    .reset_index(drop=True)
)

print("Required geographic tiles:", len(tiles))

display(tiles.head(20))

Required geographic tiles: 96

    lat_tile  lon_tile
0      -80.0     -80.0
1      -80.0     -60.0
2      -80.0     160.0
3      -60.0     -80.0
4      -60.0     -60.0
5      -60.0     -40.0
6      -60.0     140.0
7      -60.0     160.0
8      -40.0    -180.0
9      -40.0    -160.0
10     -40.0    -140.0
11     -40.0     -80.0
12     -40.0     -60.0
13     -40.0     -20.0
14     -40.0       0.0
15     -40.0      20.0
16     -40.0      40.0
17     -40.0     100.0
18     -40.0     120.0
19     -40.0     140.0

In [25]:
tile_counts = (
    era5_cells
    .groupby(["lat_tile", "lon_tile"])
    .size()
    .reset_index(name="cell_count")
    .sort_values("cell_count", ascending=False)
)

print("Total tiles:", len(tile_counts))
print("Total cells:", tile_counts["cell_count"].sum())

print("\nLargest tiles:")
display(tile_counts.head(20))

print("\nTile statistics:")
print(tile_counts["cell_count"].describe())

Total tiles: 96
Total cells: 3124

Largest tiles:

    lat_tile  lon_tile  cell_count
77      40.0       0.0         325
74      40.0     -80.0         189
76      40.0     -20.0         178
68      20.0     120.0         142
72      40.0    -140.0         125
63      20.0      20.0         123
73      40.0    -100.0         118
41       0.0     -80.0         109
78      40.0      20.0          98
90      60.0       0.0          94
50       0.0     100.0          84
58      20.0    -100.0          74
62      20.0       0.0          74
59      20.0     -80.0          70
91      60.0      20.0          69
51       0.0     120.0          68
64      20.0      40.0          59
61      20.0     -20.0          51
33     -20.0     100.0          48
45       0.0       0.0          46

Tile statistics:
count     96.000000
mean      32.541667
std       49.363937
min        1.000000
25%        5.000000
50%       15.000000
75%       35.500000
max      325.000000
Name: cell_count, dtype: float64

In [26]:
print("Instant variable units:")

for var in ["u10", "v10", "t2m"]:
    print(var, "→", instant_ds[var].attrs.get("units"))

print("\nAccumulated variable units:")

print("tp →", accum_ds["tp"].attrs.get("units"))

print("\nSample values:")

print("u10:")
print(instant_ds["u10"].values)

print("\nv10:")
print(instant_ds["v10"].values)

print("\nt2m:")
print(instant_ds["t2m"].values)

print("\ntp:")
print(accum_ds["tp"].values)

Instant variable units:
u10 → m s**-1
v10 → m s**-1
t2m → K

Accumulated variable units:
tp → m

Sample values:
u10:
[[[ 1.5779114   1.1335754   0.85232544]
  [ 1.6697083   1.3923645   2.2937317 ]
  [ 1.4831848   1.837677    2.8406067 ]]

 [[ 2.1404266   2.2576141   2.1882782 ]
  [ 1.7097626   1.9763641   3.01445   ]
  [ 1.1082001   1.6472626   2.8044891 ]]

 [[ 0.63941956  0.857193    0.9480133 ]
  [ 0.06813049  0.22731018  0.6198883 ]
  [-0.2160492   0.18922424  0.622818  ]]

 [[ 0.52511597  0.46847534  0.5729675 ]
  [ 0.2585144   0.24581909  0.03585815]
  [ 0.27609253  0.12667847 -0.11941528]]]

v10:
[[[ 1.114914    1.130539    1.099289  ]
  [ 1.2692108   1.271164    0.65104675]
  [ 0.8326874   0.686203    0.05241394]]

 [[ 0.4647522   0.69229126  0.9315491 ]
  [ 0.62197876  0.8729553   1.26651   ]
  [ 0.9911194   1.1825256   1.6034241 ]]

 [[-0.71847534 -0.4958191  -0.09347534]
  [-1.01828    -0.8366394  -0.98605347]
  [-1.0104675  -1.071991   -1.2380066 ]]

 [[-1.6524353  -1.4502869  -1.1778259 ]
  [-1.2705994  -1.0870056  -1.0000916 ]
  [-0.99227905 -0.7930603  -0.72958374]]]

t2m:
[[[277.47412 278.01514 278.67334]
  [278.07178 278.63232 279.20068]
  [278.05615 278.47607 279.10693]]

 [[276.74695 277.33093 277.90125]
  [277.26648 277.8114  278.30164]
  [277.0946  277.53015 278.0536 ]]

 [[276.26553 276.70694 277.26944]
  [276.57217 277.10733 277.7499 ]
  [276.1913  277.0624  277.78897]]

 [[280.18326 279.82974 279.5309 ]
  [280.36295 279.6852  279.22232]
  [280.31216 280.3024  279.7184 ]]]

tp:
[[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [9.5367432e-07 4.7683716e-06 4.7683716e-06]]

 [[1.5401840e-04 1.9168854e-04 1.4305115e-04]
  [7.5340271e-05 1.1253357e-04 1.3971329e-04]
  [2.7656555e-05 7.9631805e-05 9.9658966e-05]]

 [[1.9073486e-06 1.4305115e-06 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]]

 [[3.3378601e-06 1.9073486e-06 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [9.5367432e-07 9.5367432e-07 9.5367432e-07]]]

In [27]:
print("=== PRECIPITATION ATTRIBUTES ===")
print(accum_ds["tp"].attrs)

print("\n=== PRECIPITATION ENCODING ===")
print(accum_ds["tp"].encoding)

print("\n=== DATASET ATTRIBUTES ===")
print(accum_ds.attrs)

=== PRECIPITATION ATTRIBUTES ===
{'GRIB_paramId': np.int64(228), 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': np.int64(9), 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': np.int64(1), 'GRIB_stepType': 'accum', 'GRIB_gridType': 'regular_ll', 'GRIB_uvRelativeToGrid': np.int64(0), 'GRIB_NV': np.int64(0), 'GRIB_Nx': np.int64(3), 'GRIB_Ny': np.int64(3), 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'tp', 'GRIB_gridDefinitionDescription': 'Latitude/Longitude Grid', 'GRIB_iDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_iScansNegatively': np.int64(0), 'GRIB_jDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_jPointsAreConsecutive': np.int64(0), 'GRIB_jScansPositively': np.int64(0), 'GRIB_latitudeOfFirstGridPointInDegrees': np.float64(40.75), 'GRIB_latitudeOfLastGridPointInDegrees': np.float64(40.25), 'GRIB_longitudeOfFirstGridPointInDegrees': np.float64(-74.5), 'GRIB_longitudeOfLastGridPointInDegrees': np.float64(-74.0), 'GRIB_missingValue': np.float64(3.4028234663852886e+38), 'GRIB_name': 'Total precipitation', 'GRIB_shortName': 'tp', 'GRIB_totalNumber': np.int64(0), 'GRIB_units': 'm', 'long_name': 'Total precipitation', 'units': 'm', 'standard_name': 'unknown', 'GRIB_surface': np.float64(0.0)}

=== PRECIPITATION ENCODING ===
{'dtype': dtype('float32'), 'zlib': True, 'szip': False, 'zstd': False, 'bzip2': False, 'blosc': False, 'shuffle': True, 'complevel': 1, 'fletcher32': False, 'contiguous': False, 'chunksizes': (4, 3, 3), 'preferred_chunks': {'valid_time': 4, 'latitude': 3, 'longitude': 3}, 'source': 'C:\\Users\\KIIT\\OneDrive\\Desktop\\MarineGuard-AI\\ml\\era5_multi_point_test\\data_stream-oper_stepType-accum.nc', 'original_shape': (4, 3, 3), '_FillValue': np.float32(nan), 'coordinates': 'number valid_time latitude longitude expver'}

=== DATASET ATTRIBUTES ===
{'GRIB_centre': 'ecmf', 'GRIB_centreDescription': 'European Centre for Medium-Range Weather Forecasts', 'GRIB_subCentre': np.int64(0), 'Conventions': 'CF-1.7', 'institution': 'European Centre for Medium-Range Weather Forecasts', 'history': '2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.15.1/ecCodes-2.48.2 with {"source": "tmphqmw6711/data.grib", "filter_by_keys": {"stream": ["oper"], "stepType": ["accum"]}, "encode_cf": ["parameter", "time", "geography", "vertical"]}'}

In [28]:
print("=== TIME COORDINATES ===")
print(accum_ds["valid_time"].values)

print("\n=== STEP INFORMATION ===")

for key in accum_ds.coords:
    print(key, "→", accum_ds.coords[key].values)

print("\n=== TP ATTRIBUTES ===")
print(accum_ds["tp"].attrs)

=== TIME COORDINATES ===
['2024-01-01T00:00:00.000000000' '2024-01-01T06:00:00.000000000'
 '2024-01-01T12:00:00.000000000' '2024-01-01T18:00:00.000000000']

=== STEP INFORMATION ===
number → 0
valid_time → ['2024-01-01T00:00:00.000000000' '2024-01-01T06:00:00.000000000'
 '2024-01-01T12:00:00.000000000' '2024-01-01T18:00:00.000000000']
latitude → [40.75 40.5  40.25]
longitude → [-74.5  -74.25 -74.  ]
expver → ['0001' '0001' '0001' '0001']

=== TP ATTRIBUTES ===
{'GRIB_paramId': np.int64(228), 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': np.int64(9), 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': np.int64(1), 'GRIB_stepType': 'accum', 'GRIB_gridType': 'regular_ll', 'GRIB_uvRelativeToGrid': np.int64(0), 'GRIB_NV': np.int64(0), 'GRIB_Nx': np.int64(3), 'GRIB_Ny': np.int64(3), 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'tp', 'GRIB_gridDefinitionDescription': 'Latitude/Longitude Grid', 'GRIB_iDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_iScansNegatively': np.int64(0), 'GRIB_jDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_jPointsAreConsecutive': np.int64(0), 'GRIB_jScansPositively': np.int64(0), 'GRIB_latitudeOfFirstGridPointInDegrees': np.float64(40.75), 'GRIB_latitudeOfLastGridPointInDegrees': np.float64(40.25), 'GRIB_longitudeOfFirstGridPointInDegrees': np.float64(-74.5), 'GRIB_longitudeOfLastGridPointInDegrees': np.float64(-74.0), 'GRIB_missingValue': np.float64(3.4028234663852886e+38), 'GRIB_name': 'Total precipitation', 'GRIB_shortName': 'tp', 'GRIB_totalNumber': np.int64(0), 'GRIB_units': 'm', 'long_name': 'Total precipitation', 'units': 'm', 'standard_name': 'unknown', 'GRIB_surface': np.float64(0.0)}

In [29]:
import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00",
            "01:00",
            "02:00",
            "03:00",
            "04:00",
            "05:00",
            "06:00",
            "07:00",
            "08:00",
            "09:00",
            "10:00",
            "11:00",
            "12:00",
            "13:00",
            "14:00",
            "15:00",
            "16:00",
            "17:00",
            "18:00",
            "19:00",
            "20:00",
            "21:00",
            "22:00",
            "23:00"
        ],
        "area": [
            40.625,
            -74.375,
            40.375,
            -74.125
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_hourly_test.zip"
)

print("Hourly ERA5 test download completed.")

2026-10-07 23:18:35,902 INFO [2026-10-06T00:00:00Z] The [CDS Terms of Use](https://cds.climate.copernicus.eu/disclaimer-privacy) will be updated on 28 October 2026. Continued use of Copernicus Products and Services through the CDS after this date constitutes acceptance of the updated terms. If you do not accept the change, please [contact ECMWF Support](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202) before 27 October 2026.
 **[More information about the upcoming change.](https://forum.ecmwf.int/t/upcoming-cds-terms-of-use-change/15374)**
2026-10-07 23:18:37,797 INFO Request ID is 7af8a7dc-5d16-4450-80e2-36367ba34efb
2026-10-07 23:18:38,300 INFO status has been updated to successful

569a8a12c644bd9aebd86cad04f57d5.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Hourly ERA5 test download completed.

In [30]:
import zipfile

with zipfile.ZipFile("era5_hourly_test.zip", "r") as z:
    print(z.namelist())
    z.extractall("era5_hourly_test")

['data_stream-oper_stepType-instant.nc', 'data_stream-oper_stepType-accum.nc']

In [31]:
import xarray as xr

accum_hourly = xr.open_dataset(
    "era5_hourly_test/data_stream-oper_stepType-accum.nc",
    engine="netcdf4"
)

print(accum_hourly)

<xarray.Dataset> Size: 696B
Dimensions:     (valid_time: 24, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 96B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-26T17:22 GRIB to CDM+CF via cfgrib-0.9.1...

In [32]:
print("=== HOURLY PRECIPITATION ===")

for time, value in zip(
    accum_hourly["valid_time"].values,
    accum_hourly["tp"].values[:, 0, 0]
):
    print(time, "→", value, "m")

=== HOURLY PRECIPITATION ===
2024-01-01T00:00:00.000000000 → 0.0 m
2024-01-01T01:00:00.000000000 → 0.0 m
2024-01-01T02:00:00.000000000 → 4.5776367e-05 m
2024-01-01T03:00:00.000000000 → 5.2452087e-06 m
2024-01-01T04:00:00.000000000 → 3.862381e-05 m
2024-01-01T05:00:00.000000000 → 0.00015974045 m
2024-01-01T06:00:00.000000000 → 0.00011253357 m
2024-01-01T07:00:00.000000000 → 0.0 m
2024-01-01T08:00:00.000000000 → 0.0 m
2024-01-01T09:00:00.000000000 → 0.0 m
2024-01-01T10:00:00.000000000 → 0.0 m
2024-01-01T11:00:00.000000000 → 0.0 m
2024-01-01T12:00:00.000000000 → 0.0 m
2024-01-01T13:00:00.000000000 → 0.0 m
2024-01-01T14:00:00.000000000 → 0.0 m
2024-01-01T15:00:00.000000000 → 0.0 m
2024-01-01T16:00:00.000000000 → 0.0 m
2024-01-01T17:00:00.000000000 → 0.0 m
2024-01-01T18:00:00.000000000 → 0.0 m
2024-01-01T19:00:00.000000000 → 8.583069e-06 m
2024-01-01T20:00:00.000000000 → 4.7683716e-07 m
2024-01-01T21:00:00.000000000 → 0.0 m
2024-01-01T22:00:00.000000000 → 0.0 m
2024-01-01T23:00:00.000000000 → 0.0 m

In [33]:
import pandas as pd
import numpy as np

weather_test = pd.DataFrame({
    "valid_time": accum_hourly["valid_time"].values,
    "latitude": accum_hourly["latitude"].values[0],
    "longitude": accum_hourly["longitude"].values[0],
    "precipitation_m": accum_hourly["tp"].values[:, 0, 0]
})

weather_test["precipitation_mm"] = (
    weather_test["precipitation_m"] * 1000
)

weather_test.head(10)

           valid_time  latitude  longitude  precipitation_m  precipitation_mm
0 2024-01-01 00:00:00      40.5     -74.25         0.000000          0.000000
1 2024-01-01 01:00:00      40.5     -74.25         0.000000          0.000000
2 2024-01-01 02:00:00      40.5     -74.25         0.000046          0.045776
3 2024-01-01 03:00:00      40.5     -74.25         0.000005          0.005245
4 2024-01-01 04:00:00      40.5     -74.25         0.000039          0.038624
5 2024-01-01 05:00:00      40.5     -74.25         0.000160          0.159740
6 2024-01-01 06:00:00      40.5     -74.25         0.000113          0.112534
7 2024-01-01 07:00:00      40.5     -74.25         0.000000          0.000000
8 2024-01-01 08:00:00      40.5     -74.25         0.000000          0.000000
9 2024-01-01 09:00:00      40.5     -74.25         0.000000          0.000000

In [34]:
instant_hourly = xr.open_dataset(
    "era5_hourly_test/data_stream-oper_stepType-instant.nc",
    engine="netcdf4"
)

print(instant_hourly)

<xarray.Dataset> Size: 888B
Dimensions:     (valid_time: 24, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 96B ...
    v10         (valid_time, latitude, longitude) float32 96B ...
    t2m         (valid_time, latitude, longitude) float32 96B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-26T17:22 GRIB to CDM+CF via cfgrib-0.9.1...

In [35]:
weather_test = pd.DataFrame({
    "valid_time": instant_hourly["valid_time"].values,
    "latitude": instant_hourly["latitude"].values[0],
    "longitude": instant_hourly["longitude"].values[0],

    "u10": instant_hourly["u10"].values[:, 0, 0],
    "v10": instant_hourly["v10"].values[:, 0, 0],
    "temperature_k": instant_hourly["t2m"].values[:, 0, 0],

    "precipitation_m": accum_hourly["tp"].values[:, 0, 0]
})

weather_test.head()

,valid_time,latitude,longitude,u10,v10,temperature_k,precipitation_m
0,2024-01-01 00:00:00,40.5,-74.25,1.392365,1.271164,278.632080,0.000000
1,2024-01-01 01:00:00,40.5,-74.25,1.411575,1.185440,278.464844,0.000000
2,2024-01-01 02:00:00,40.5,-74.25,1.194931,1.098785,277.939941,0.000046
3,2024-01-01 03:00:00,40.5,-74.25,1.514572,1.217392,277.829346,0.000005
4,2024-01-01 04:00:00,40.5,-74.25,1.669922,1.202515,277.924805,0.000039

In [36]:
weather_test["wind_speed_ms"] = np.sqrt(
    weather_test["u10"]**2 +
    weather_test["v10"]**2
)

weather_test["temperature_c"] = (
    weather_test["temperature_k"] - 273.15
)

weather_test["precipitation_mm"] = (
    weather_test["precipitation_m"] * 1000
)

In [37]:
weather_test[
    [
        "valid_time",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].head(10)

           valid_time  wind_speed_ms  temperature_c  precipitation_mm
0 2024-01-01 00:00:00       1.885348       5.482086          0.000000
1 2024-01-01 01:00:00       1.843316       5.314850          0.000000
2 2024-01-01 02:00:00       1.623327       4.789948          0.045776
3 2024-01-01 03:00:00       1.943186       4.679352          0.005245
4 2024-01-01 04:00:00       2.057834       4.774811          0.038624
5 2024-01-01 05:00:00       2.405361       5.082428          0.159740
6 2024-01-01 06:00:00       2.160571       4.661285          0.112534
7 2024-01-01 07:00:00       1.818360       4.855377          0.000000
8 2024-01-01 08:00:00       1.352087       4.596344          0.000000
9 2024-01-01 09:00:00       1.142918       4.827545          0.000000

In [38]:
print("Rows:", len(weather_test))

print("\nMissing values:")
print(weather_test[
    [
        "valid_time",
        "latitude",
        "longitude",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].isna().sum())

print("\nRanges:")
print("Wind speed:", weather_test["wind_speed_ms"].min(),
      "to", weather_test["wind_speed_ms"].max(), "m/s")

print("Temperature:", weather_test["temperature_c"].min(),
      "to", weather_test["temperature_c"].max(), "°C")

print("Precipitation:", weather_test["precipitation_mm"].min(),
      "to", weather_test["precipitation_mm"].max(), "mm")

Rows: 24

Missing values:
valid_time          0
latitude            0
longitude           0
wind_speed_ms       0
temperature_c       0
precipitation_mm    0
dtype: int64

Ranges:
Wind speed: 0.500170111656189 to 2.4053609371185303 m/s
Temperature: 3.276031494140625 to 6.535064697265625 °C
Precipitation: 0.0 to 0.15974044799804688 mm

In [39]:
weather_clean = weather_test[
    [
        "valid_time",
        "latitude",
        "longitude",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].copy()

weather_clean.head(10)

,valid_time,latitude,longitude,wind_speed_ms,temperature_c,precipitation_mm
0,2024-01-01 00:00:00,40.5,-74.25,1.885348,5.482086,0.000000
1,2024-01-01 01:00:00,40.5,-74.25,1.843316,5.314850,0.000000
2,2024-01-01 02:00:00,40.5,-74.25,1.623327,4.789948,0.045776
3,2024-01-01 03:00:00,40.5,-74.25,1.943186,4.679352,0.005245
4,2024-01-01 04:00:00,40.5,-74.25,2.057834,4.774811,0.038624
5,2024-01-01 05:00:00,40.5,-74.25,2.405361,5.082428,0.159740
6,2024-01-01 06:00:00,40.5,-74.25,2.160571,4.661285,0.112534
7,2024-01-01 07:00:00,40.5,-74.25,1.818360,4.855377,0.000000
8,2024-01-01 08:00:00,40.5,-74.25,1.352087,4.596344,0.000000
9,2024-01-01 09:00:00,40.5,-74.25,1.142918,4.827545,0.000000

In [40]:
weather_clean["era5_cell"] = (
    weather_clean["latitude"].astype(str)
    + "_"
    + weather_clean["longitude"].astype(str)
)

weather_clean.head()

,valid_time,latitude,longitude,wind_speed_ms,temperature_c,precipitation_mm,era5_cell
0,2024-01-01 00:00:00,40.5,-74.25,1.885348,5.482086,0.000000,40.5_-74.25
1,2024-01-01 01:00:00,40.5,-74.25,1.843316,5.314850,0.000000,40.5_-74.25
2,2024-01-01 02:00:00,40.5,-74.25,1.623327,4.789948,0.045776,40.5_-74.25
3,2024-01-01 03:00:00,40.5,-74.25,1.943186,4.679352,0.005245,40.5_-74.25
4,2024-01-01 04:00:00,40.5,-74.25,2.057834,4.774811,0.038624,40.5_-74.25

In [41]:
print("Total weather rows:", len(weather_clean))

print(
    "Unique ERA5 cells:",
    weather_clean["era5_cell"].nunique()
)

print(
    "\nCells:",
    weather_clean["era5_cell"].unique()
)

Total weather rows: 24
Unique ERA5 cells: 1

Cells: ['40.5_-74.25']

In [42]:
port_cell_counts = (
    weather_locations
    .groupby(["era5_lat", "era5_lon"])
    .size()
    .reset_index(name="port_count")
    .sort_values("port_count", ascending=False)
)

print("Total ERA5 cells:", len(port_cell_counts))
print("\nLargest ERA5 cells:")
display(port_cell_counts.head(10))

Total ERA5 cells: 3124

Largest ERA5 cells:

      era5_lat  era5_lon  port_count
1571     38.00   -122.25           9
1698     40.50    -74.25           9
1711     40.75    -74.00           8
2836     59.50     24.75           7
1717     40.75     14.00           6
1190     29.75    -95.25           5
2642     56.00     -3.25           5
1385     34.75    134.75           5
2237     47.50   -122.50           5
1669     39.75    -75.50           5

In [43]:
era5_download_list = era5_cells.copy()

era5_download_list["era5_cell"] = (
    era5_download_list["era5_lat"].astype(str)
    + "_"
    + era5_download_list["era5_lon"].astype(str)
)

print("Total ERA5 cells to download:",
      len(era5_download_list))

display(era5_download_list.head(10))

Total ERA5 cells to download: 3124

   era5_lat  era5_lon  lat_tile  lon_tile      era5_cell
0     40.50    -74.25      40.0     -80.0    40.5_-74.25
1    -13.25     50.00     -20.0      40.0    -13.25_50.0
2     -5.25     39.75     -20.0      20.0    -5.25_39.75
3     -6.75     39.25     -20.0      20.0    -6.75_39.25
4     36.75     36.25      20.0      20.0    36.75_36.25
5     -5.50    106.25     -20.0     100.0    -5.5_106.25
6     36.25     -5.25      20.0     -20.0    36.25_-5.25
7     43.75    -69.50      40.0     -80.0    43.75_-69.5
8    -22.75    -43.25     -40.0     -60.0  -22.75_-43.25
9     28.00     35.25      20.0      20.0     28.0_35.25

In [44]:
tile_counts = (
    era5_download_list
    .groupby(["lat_tile", "lon_tile"])
    .size()
    .reset_index(name="cell_count")
    .sort_values("cell_count", ascending=False)
)

print("Total geographic tiles:", len(tile_counts))
print("Total ERA5 cells:", tile_counts["cell_count"].sum())

print("\nLargest tiles:")
display(tile_counts.head(10))

Total geographic tiles: 96
Total ERA5 cells: 3124

Largest tiles:

    lat_tile  lon_tile  cell_count
77      40.0       0.0         325
74      40.0     -80.0         189
76      40.0     -20.0         178
68      20.0     120.0         142
72      40.0    -140.0         125
63      20.0      20.0         123
73      40.0    -100.0         118
41       0.0     -80.0         109
78      40.0      20.0          98
90      60.0       0.0          94

In [45]:
largest_tile = tile_counts.iloc[0]

print("Latitude tile:", largest_tile["lat_tile"])
print("Longitude tile:", largest_tile["lon_tile"])
print("ERA5 cells:", largest_tile["cell_count"])

largest_tile_cells = era5_download_list[
    (era5_download_list["lat_tile"] == largest_tile["lat_tile"]) &
    (era5_download_list["lon_tile"] == largest_tile["lon_tile"])
].copy()

print("\nCells in this tile:", len(largest_tile_cells))

display(largest_tile_cells.head(20))

Latitude tile: 40.0
Longitude tile: 0.0
ERA5 cells: 325.0

Cells in this tile: 325

     era5_lat  era5_lon  lat_tile  lon_tile    era5_cell
56      49.75      0.25      40.0       0.0   49.75_0.25
57      45.25     12.25      40.0       0.0  45.25_12.25
79      42.75     18.00      40.0       0.0   42.75_18.0
80      43.50     10.25      40.0       0.0   43.5_10.25
81      43.75      7.50      40.0       0.0    43.75_7.5
92      41.75     12.25      40.0       0.0  41.75_12.25
114     43.75      7.25      40.0       0.0   43.75_7.25
117     43.00      6.00      40.0       0.0     43.0_6.0
119     42.25     14.50      40.0       0.0   42.25_14.5
124     40.50     17.25      40.0       0.0   40.5_17.25
131     43.00     17.50      40.0       0.0    43.0_17.5
180     43.50      5.00      40.0       0.0     43.5_5.0
188     49.25      0.00      40.0       0.0    49.25_0.0
193     40.00      0.00      40.0       0.0     40.0_0.0
195     41.50      9.25      40.0       0.0    41.5_9.25
203     43.50      6.75      40.0       0.0    43.5_6.75
206     43.00      3.00      40.0       0.0     43.0_3.0
209     41.50     16.00      40.0       0.0    41.5_16.0
210     42.00     11.75      40.0       0.0   42.0_11.75
211     43.00     17.25      40.0       0.0   43.0_17.25

In [46]:
print("Minimum latitude:", largest_tile_cells["era5_lat"].min())
print("Maximum latitude:", largest_tile_cells["era5_lat"].max())

print("Minimum longitude:", largest_tile_cells["era5_lon"].min())
print("Maximum longitude:", largest_tile_cells["era5_lon"].max())

Minimum latitude: 40.0
Maximum latitude: 59.75
Minimum longitude: -0.0
Maximum longitude: 19.5

In [47]:
import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00",
            "01:00",
            "02:00",
            "03:00",
            "04:00",
            "05:00",
            "06:00",
            "07:00",
            "08:00",
            "09:00",
            "10:00",
            "11:00",
            "12:00",
            "13:00",
            "14:00",
            "15:00",
            "16:00",
            "17:00",
            "18:00",
            "19:00",
            "20:00",
            "21:00",
            "22:00",
            "23:00"
        ],
        "area": [
            59.75,
            0.0,
            40.0,
            19.5
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_tile_test.zip"
)

print("Tile test download completed.")

2026-10-07 23:18:43,664 INFO [2026-10-06T00:00:00Z] The [CDS Terms of Use](https://cds.climate.copernicus.eu/disclaimer-privacy) will be updated on 28 October 2026. Continued use of Copernicus Products and Services through the CDS after this date constitutes acceptance of the updated terms. If you do not accept the change, please [contact ECMWF Support](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202) before 27 October 2026.
 **[More information about the upcoming change.](https://forum.ecmwf.int/t/upcoming-cds-terms-of-use-change/15374)**
2026-10-07 23:18:48,952 INFO Request ID is d740f718-5c7a-4e8e-9dd9-b6b6de414890
2026-10-07 23:18:49,174 INFO status has been updated to successful

c3d0ae1ac314cc6a84a1baaf5683fd61.zip:   0%|          | 0.00/1.13M [00:00<?, ?B/s]

Tile test download completed.

In [48]:
import zipfile
import xarray as xr

zip_file = "era5_tile_test.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

    z.extractall("era5_tile_test")

instant_file = "era5_tile_test/data_stream-oper_stepType-instant.nc"
accum_file = "era5_tile_test/data_stream-oper_stepType-accum.nc"

instant_ds = xr.open_dataset(instant_file, engine="netcdf4")
accum_ds = xr.open_dataset(accum_file, engine="netcdf4")

print("\n=== INSTANT DATA ===")
print(instant_ds)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

=== INSTANT DATA ===
<xarray.Dataset> Size: 2MB
Dimensions:     (valid_time: 24, latitude: 80, longitude: 79)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 640B 59.75 59.5 59.25 ... 40.5 40.25 40.0
  * longitude   (longitude) float64 632B 0.0 0.25 0.5 0.75 ... 19.0 19.25 19.5
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 607kB ...
    v10         (valid_time, latitude, longitude) float32 607kB ...
    t2m         (valid_time, latitude, longitude) float32 607kB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-27T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 609kB
Dimensions:     (valid_time: 24, latitude: 80, longitude: 79)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 640B 59.75 59.5 59.25 ... 40.5 40.25 40.0
  * longitude   (longitude) float64 632B 0.0 0.25 0.5 0.75 ... 19.0 19.25 19.5
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 607kB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-27T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

In [49]:
print("Downloaded grid cells:", len(instant_ds.latitude) * len(instant_ds.longitude))
print("Required cells:", len(largest_tile_cells))

print("\nRequired latitude range:")
print(largest_tile_cells["era5_lat"].min(), "to", largest_tile_cells["era5_lat"].max())

print("\nRequired longitude range:")
print(largest_tile_cells["era5_lon"].min(), "to", largest_tile_cells["era5_lon"].max())

Downloaded grid cells: 6320
Required cells: 325

Required latitude range:
40.0 to 59.75

Required longitude range:
-0.0 to 19.5

In [50]:
required_cells = set(
    zip(
        largest_tile_cells["era5_lat"],
        largest_tile_cells["era5_lon"]
    )
)

downloaded_cells = set(
    (float(lat), float(lon))
    for lat in instant_ds.latitude.values
    for lon in instant_ds.longitude.values
)

matched_cells = required_cells.intersection(downloaded_cells)
missing_cells = required_cells - downloaded_cells

print("Required cells:", len(required_cells))
print("Downloaded cells:", len(downloaded_cells))
print("Matched cells:", len(matched_cells))
print("Missing cells:", len(missing_cells))

Required cells: 325
Downloaded cells: 6320
Matched cells: 325
Missing cells: 0

In [51]:
import pandas as pd
import numpy as np

required_cells_df = largest_tile_cells[
    ["era5_lat", "era5_lon"]
].drop_duplicates().reset_index(drop=True)

rows = []

for _, cell in required_cells_df.iterrows():

    lat = cell["era5_lat"]
    lon = cell["era5_lon"]

    u10 = instant_ds["u10"].sel(
        latitude=lat,
        longitude=lon
    ).values

    v10 = instant_ds["v10"].sel(
        latitude=lat,
        longitude=lon
    ).values

    t2m = instant_ds["t2m"].sel(
        latitude=lat,
        longitude=lon
    ).values

    tp = accum_ds["tp"].sel(
        latitude=lat,
        longitude=lon
    ).values

    wind_speed = np.sqrt(u10**2 + v10**2)
    temperature_c = t2m - 273.15
    precipitation_mm = tp * 1000

    for i, time in enumerate(instant_ds["valid_time"].values):

        rows.append({
            "valid_time": time,
            "latitude": lat,
            "longitude": lon,
            "wind_speed_ms": wind_speed[i],
            "temperature_c": temperature_c[i],
            "precipitation_mm": precipitation_mm[i]
        })

tile_weather = pd.DataFrame(rows)

print("Rows:", len(tile_weather))
print("Unique cells:", tile_weather[["latitude", "longitude"]].drop_duplicates().shape[0])

display(tile_weather.head(10))

Rows: 7800
Unique cells: 325

,valid_time,latitude,longitude,wind_speed_ms,temperature_c,precipitation_mm
0,2024-01-01 00:00:00,49.75,0.25,13.289212,8.900055,1.143456
1,2024-01-01 01:00:00,49.75,0.25,12.621182,9.051178,0.776291
2,2024-01-01 02:00:00,49.75,0.25,12.784980,8.895416,0.783920
3,2024-01-01 03:00:00,49.75,0.25,12.093224,9.230133,0.593662
4,2024-01-01 04:00:00,49.75,0.25,11.260066,9.526764,0.134945
5,2024-01-01 05:00:00,49.75,0.25,10.336418,9.601959,0.037193
6,2024-01-01 06:00:00,49.75,0.25,9.984933,9.557770,0.068665
7,2024-01-01 07:00:00,49.75,0.25,9.775416,9.449127,0.229836
8,2024-01-01 08:00:00,49.75,0.25,9.373335,9.026031,0.269413
9,2024-01-01 09:00:00,49.75,0.25,8.856035,8.766998,0.358582

In [52]:
print("=== DATASET VALIDATION ===")

print("\nShape:")
print(tile_weather.shape)

print("\nMissing values:")
print(tile_weather.isna().sum())

print("\nDuplicate rows:")
print(tile_weather.duplicated().sum())

print("\nUnique cells:")
print(
    tile_weather[["latitude", "longitude"]]
    .drop_duplicates()
    .shape[0]
)

print("\nWind speed range:")
print(
    tile_weather["wind_speed_ms"].min(),
    "to",
    tile_weather["wind_speed_ms"].max(),
    "m/s"
)

print("\nTemperature range:")
print(
    tile_weather["temperature_c"].min(),
    "to",
    tile_weather["temperature_c"].max(),
    "°C"
)

print("\nPrecipitation range:")
print(
    tile_weather["precipitation_mm"].min(),
    "to",
    tile_weather["precipitation_mm"].max(),
    "mm"
)

=== DATASET VALIDATION ===

Shape:
(7800, 6)

Missing values:
valid_time          0
latitude            0
longitude           0
wind_speed_ms       0
temperature_c       0
precipitation_mm    0
dtype: int64

Duplicate rows:
0

Unique cells:
325

Wind speed range:
0.10311661660671234 to 17.296846389770508 m/s

Temperature range:
-6.004241943359375 to 17.478668212890625 °C

Precipitation range:
0.0 to 3.1604766845703125 mm

In [53]:
tile_weather.to_csv(
    "era5_tile_40_0_2024_01_01.csv",
    index=False
)

print("Saved successfully.")
print("Rows:", len(tile_weather))

Saved successfully.
Rows: 7800

In [54]:
# Show a few available tiles
display(tiles.head(10))

print("Total geographic tiles:", len(tiles))

   lat_tile  lon_tile
0     -80.0     -80.0
1     -80.0     -60.0
2     -80.0     160.0
3     -60.0     -80.0
4     -60.0     -60.0
5     -60.0     -40.0
6     -60.0     140.0
7     -60.0     160.0
8     -40.0    -180.0
9     -40.0    -160.0

Total geographic tiles: 96

In [55]:
southern_tiles = tiles[
    tiles["lat_tile"] < 0
].copy()

print("Available southern-hemisphere tiles:", len(southern_tiles))

display(
    southern_tiles.head(20)
)

Available southern-hemisphere tiles: 37

    lat_tile  lon_tile
0      -80.0     -80.0
1      -80.0     -60.0
2      -80.0     160.0
3      -60.0     -80.0
4      -60.0     -60.0
5      -60.0     -40.0
6      -60.0     140.0
7      -60.0     160.0
8      -40.0    -180.0
9      -40.0    -160.0
10     -40.0    -140.0
11     -40.0     -80.0
12     -40.0     -60.0
13     -40.0     -20.0
14     -40.0       0.0
15     -40.0      20.0
16     -40.0      40.0
17     -40.0     100.0
18     -40.0     120.0
19     -40.0     140.0

In [56]:
second_tile = tiles[
    (tiles["lat_tile"] == -40.0) &
    (tiles["lon_tile"] == -20.0)
].iloc[0]

second_tile_cells = era5_download_list[
    (era5_download_list["lat_tile"] == second_tile["lat_tile"]) &
    (era5_download_list["lon_tile"] == second_tile["lon_tile"])
].copy()

print("Latitude tile:", second_tile["lat_tile"])
print("Longitude tile:", second_tile["lon_tile"])
print("Required ERA5 cells:", len(second_tile_cells))

print("\nLatitude range:")
print(
    second_tile_cells["era5_lat"].min(),
    "to",
    second_tile_cells["era5_lat"].max()
)

print("\nLongitude range:")
print(
    second_tile_cells["era5_lon"].min(),
    "to",
    second_tile_cells["era5_lon"].max()
)

display(second_tile_cells.head(10))

Latitude tile: -40.0
Longitude tile: -20.0
Required ERA5 cells: 1

Latitude range:
-37.0 to -37.0

Longitude range:
-12.25 to -12.25

      era5_lat  era5_lon  lat_tile  lon_tile     era5_cell
1705     -37.0    -12.25     -40.0     -20.0  -37.0_-12.25

In [57]:
client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00", "01:00", "02:00", "03:00",
            "04:00", "05:00", "06:00", "07:00",
            "08:00", "09:00", "10:00", "11:00",
            "12:00", "13:00", "14:00", "15:00",
            "16:00", "17:00", "18:00", "19:00",
            "20:00", "21:00", "22:00", "23:00"
        ],
        "area": [
            -20.0,
            -40.0,
            -40.0,
            0.0
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_tile_test_2.zip"
)

print("Second tile test download completed.")

2026-10-07 23:18:58,073 INFO Request ID is 5b5fe844-d54e-4dd8-985a-7d6bc28d4a14
2026-10-07 23:18:58,370 INFO status has been updated to successful

750c103ea272c35d70ec9b07e69ff77.zip:   0%|          | 0.00/2.05M [00:00<?, ?B/s]

Second tile test download completed.

In [58]:
import zipfile
import xarray as xr

zip_file = "era5_tile_test_2.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

    z.extractall("era5_tile_test_2")

instant_file = "era5_tile_test_2/data_stream-oper_stepType-instant.nc"
accum_file = "era5_tile_test_2/data_stream-oper_stepType-accum.nc"

instant_ds_2 = xr.open_dataset(
    instant_file,
    engine="netcdf4"
)

accum_ds_2 = xr.open_dataset(
    accum_file,
    engine="netcdf4"
)

print("\n=== INSTANT DATA ===")
print(instant_ds_2)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds_2)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

=== INSTANT DATA ===
<xarray.Dataset> Size: 4MB
Dimensions:     (valid_time: 24, latitude: 81, longitude: 161)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 648B -20.0 -20.25 -20.5 ... -39.75 -40.0
  * longitude   (longitude) float64 1kB -40.0 -39.75 -39.5 ... -0.5 -0.25 0.0
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 1MB ...
    v10         (valid_time, latitude, longitude) float32 1MB ...
    t2m         (valid_time, latitude, longitude) float32 1MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-29T17:38 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 1MB
Dimensions:     (valid_time: 24, latitude: 81, longitude: 161)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 648B -20.0 -20.25 -20.5 ... -39.75 -40.0
  * longitude   (longitude) float64 1kB -40.0 -39.75 -39.5 ... -0.5 -0.25 0.0
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 1MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-29T17:38 GRIB to CDM+CF via cfgrib-0.9.1...

In [59]:
required_cells_2 = set(
    zip(
        second_tile_cells["era5_lat"],
        second_tile_cells["era5_lon"]
    )
)

downloaded_cells_2 = set(
    (float(lat), float(lon))
    for lat in instant_ds_2.latitude.values
    for lon in instant_ds_2.longitude.values
)

matched_cells_2 = required_cells_2.intersection(downloaded_cells_2)
missing_cells_2 = required_cells_2 - downloaded_cells_2

print("Required cells:", len(required_cells_2))
print("Downloaded cells:", len(downloaded_cells_2))
print("Matched cells:", len(matched_cells_2))
print("Missing cells:", len(missing_cells_2))

Required cells: 1
Downloaded cells: 13041
Matched cells: 1
Missing cells: 0

In [60]:
cell = second_tile_cells.iloc[0]

lat = cell["era5_lat"]
lon = cell["era5_lon"]

print("Selected ERA5 cell:")
print("Latitude:", lat)
print("Longitude:", lon)

Selected ERA5 cell:
Latitude: -37.0
Longitude: -12.25

In [61]:
u10_selected = instant_ds_2["u10"].sel(
    latitude=lat,
    longitude=lon
)

print(u10_selected)

<xarray.DataArray 'u10' (valid_time: 24)> Size: 96B
[24 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             165
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m s**-1
    long_name:                                10 metre U wind component
    units:                                    m s**-1
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [62]:
v10_selected = instant_ds_2["v10"].sel(
    latitude=lat,
    longitude=lon
)

print(v10_selected)

<xarray.DataArray 'v10' (valid_time: 24)> Size: 96B
[24 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             166
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m s**-1
    long_name:                                10 metre V wind component
    units:                                    m s**-1
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [63]:
wind_speed_selected = np.sqrt(
    u10_selected**2 +
    v10_selected**2
)

print(wind_speed_selected)

<xarray.DataArray (valid_time: 24)> Size: 96B
array([7.9818926, 7.5873837, 6.918569 , 6.0078244, 5.556516 , 5.7806463,
       6.6663322, 7.7187924, 8.290838 , 8.194231 , 7.5700107, 8.004541 ,
       8.522417 , 8.873473 , 9.063563 , 9.053523 , 9.156946 , 8.58687  ,
       7.8792615, 6.5186806, 4.93169  , 3.72861  , 3.693157 , 3.601091 ],
      dtype=float32)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B '0001' '0001' '0001' ... '0001' '0001'
    number      int64 8B 0
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/27)
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    GRIB_gridType:                            regular_ll
    ...                                       ...
    GRIB_missingValue:                        3.4028234663852886e+38
    GRIB_totalNumber:                         0
    GRIB_units:                               m s**-1
    units:                                    m s**-1
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [64]:
#2-metre temperature.
t2m_selected = instant_ds_2["t2m"].sel(
    latitude=lat,
    longitude=lon
)
print(t2m_selected)

<xarray.DataArray 't2m' (valid_time: 24)> Size: 96B
[24 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             167
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               K
    long_name:                                2 metre temperature
    units:                                    K
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [65]:
temperature_c_selected = t2m_selected - 273.15

print(temperature_c_selected)

<xarray.DataArray 't2m' (valid_time: 24)> Size: 96B
array([19.07608 , 18.994781, 18.911285, 18.8378  , 18.735748, 18.567047,
       18.493317, 18.54483 , 18.481354, 18.440826, 18.619781, 18.679596,
       18.750397, 18.838531, 18.96109 , 19.06607 , 19.10611 , 19.014313,
       18.832184, 18.506256, 18.217682, 17.93277 , 17.532135, 17.324127],
      dtype=float32)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             167
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               K
    long_name:                                2 metre temperature
    units:                                    K
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [66]:
tp_selected = accum_ds_2["tp"].sel(
    latitude=lat,
    longitude=lon
)

print(tp_selected)

<xarray.DataArray 'tp' (valid_time: 24)> Size: 96B
[24 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             228
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            accum
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m
    long_name:                                Total precipitation
    units:                                    m
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [67]:
precipitation_mm_selected = tp_selected * 1000

print(precipitation_mm_selected)

<xarray.DataArray 'tp' (valid_time: 24)> Size: 96B
array([2.9563904e-02, 1.2063980e-01, 3.8146973e-01, 5.2785873e-01,
       7.5054169e-01, 1.0514259e+00, 1.2788773e+00, 8.7165833e-01,
       3.6096573e-01, 2.1076202e-01, 3.8146973e-03, 2.5749207e-02,
       2.6226044e-02, 4.7683716e-03, 2.8610229e-03, 3.5285950e-02,
       2.4414062e-01, 4.6539307e-01, 1.6331673e+00, 8.5830688e-03,
       0.0000000e+00, 9.5367432e-04, 9.5367432e-04, 0.0000000e+00],
      dtype=float32)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
    number      int64 8B ...
    latitude    float64 8B -37.0
    longitude   float64 8B -12.25
Attributes: (12/32)
    GRIB_paramId:                             228
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      13041
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            accum
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m
    long_name:                                Total precipitation
    units:                                    m
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [68]:
weather_cell_2 = pd.DataFrame({
    "valid_time": instant_ds_2["valid_time"].values,
    "latitude": lat,
    "longitude": lon,
    "wind_speed_ms": wind_speed_selected.values,
    "temperature_c": temperature_c_selected.values,
    "precipitation_mm": precipitation_mm_selected.values
})

print(weather_cell_2)

            valid_time  latitude  longitude  wind_speed_ms  temperature_c  \
0  2024-01-01 00:00:00     -37.0     -12.25       7.981893      19.076080
1  2024-01-01 01:00:00     -37.0     -12.25       7.587384      18.994781
2  2024-01-01 02:00:00     -37.0     -12.25       6.918569      18.911285
3  2024-01-01 03:00:00     -37.0     -12.25       6.007824      18.837799
4  2024-01-01 04:00:00     -37.0     -12.25       5.556516      18.735748
5  2024-01-01 05:00:00     -37.0     -12.25       5.780646      18.567047
6  2024-01-01 06:00:00     -37.0     -12.25       6.666332      18.493317
7  2024-01-01 07:00:00     -37.0     -12.25       7.718792      18.544830
8  2024-01-01 08:00:00     -37.0     -12.25       8.290838      18.481354
9  2024-01-01 09:00:00     -37.0     -12.25       8.194231      18.440826
10 2024-01-01 10:00:00     -37.0     -12.25       7.570011      18.619781
11 2024-01-01 11:00:00     -37.0     -12.25       8.004541      18.679596
12 2024-01-01 12:00:00     -37.0     -12.25       8.522417      18.750397
13 2024-01-01 13:00:00     -37.0     -12.25       8.873473      18.838531
14 2024-01-01 14:00:00     -37.0     -12.25       9.063563      18.961090
15 2024-01-01 15:00:00     -37.0     -12.25       9.053523      19.066071
16 2024-01-01 16:00:00     -37.0     -12.25       9.156946      19.106110
17 2024-01-01 17:00:00     -37.0     -12.25       8.586870      19.014313
18 2024-01-01 18:00:00     -37.0     -12.25       7.879261      18.832184
19 2024-01-01 19:00:00     -37.0     -12.25       6.518681      18.506256
20 2024-01-01 20:00:00     -37.0     -12.25       4.931690      18.217682
21 2024-01-01 21:00:00     -37.0     -12.25       3.728610      17.932770
22 2024-01-01 22:00:00     -37.0     -12.25       3.693157      17.532135
23 2024-01-01 23:00:00     -37.0     -12.25       3.601091      17.324127

    precipitation_mm
0           0.029564
1           0.120640
2           0.381470
3           0.527859
4           0.750542
5           1.051426
6           1.278877
7           0.871658
8           0.360966
9           0.210762
10          0.003815
11          0.025749
12          0.026226
13          0.004768
14          0.002861
15          0.035286
16          0.244141
17          0.465393
18          1.633167
19          0.008583
20          0.000000
21          0.000954
22          0.000954
23          0.000000

In [69]:
print("Shape:", weather_cell_2.shape)

print("\nMissing values:")
print(weather_cell_2.isnull().sum())

print("\nDuplicate rows:", weather_cell_2.duplicated().sum())

print("\nData types:")
print(weather_cell_2.dtypes)

print("\nValue ranges:")
print("Wind speed:", weather_cell_2["wind_speed_ms"].min(),
      "to", weather_cell_2["wind_speed_ms"].max(), "m/s")

print("Temperature:", weather_cell_2["temperature_c"].min(),
      "to", weather_cell_2["temperature_c"].max(), "°C")

print("Precipitation:", weather_cell_2["precipitation_mm"].min(),
      "to", weather_cell_2["precipitation_mm"].max(), "mm")

Shape: (24, 6)

Missing values:
valid_time          0
latitude            0
longitude           0
wind_speed_ms       0
temperature_c       0
precipitation_mm    0
dtype: int64

Duplicate rows: 0

Data types:
valid_time          datetime64[ns]
latitude                   float64
longitude                  float64
wind_speed_ms              float32
temperature_c              float32
precipitation_mm           float32
dtype: object

Value ranges:
Wind speed: 3.601090908050537 to 9.156946182250977 m/s
Temperature: 17.324127197265625 to 19.106109619140625 °C
Precipitation: 0.0 to 1.6331672668457031 mm

In [70]:
era5_10deg = era5_download_list.copy()

era5_10deg["lat_chunk"] = (
    np.floor(era5_10deg["era5_lat"] / 10) * 10
)

era5_10deg["lon_chunk"] = (
    np.floor(era5_10deg["era5_lon"] / 10) * 10
)

chunks_10deg = (
    era5_10deg[
        ["lat_chunk", "lon_chunk"]
    ]
    .drop_duplicates()
    .sort_values(["lat_chunk", "lon_chunk"])
    .reset_index(drop=True)
)

print("Required ERA5 cells:", len(era5_download_list))
print("10° × 10° chunks:", len(chunks_10deg))

display(chunks_10deg.head(20))

Required ERA5 cells: 3124
10° × 10° chunks: 218

    lat_chunk  lon_chunk
0       -80.0      160.0
1       -70.0      -70.0
2       -70.0      -60.0
3       -70.0      -50.0
4       -60.0      -80.0
5       -60.0      -70.0
6       -60.0      -60.0
7       -60.0      -40.0
8       -50.0      -80.0
9       -50.0      -70.0
10      -50.0      140.0
11      -50.0      160.0
12      -50.0      170.0
13      -40.0      -80.0
14      -40.0      -70.0
15      -40.0      -60.0
16      -40.0      -20.0
17      -40.0       10.0
18      -40.0       20.0
19      -40.0      110.0

In [71]:
era5_5deg = era5_download_list.copy()

era5_5deg["lat_chunk"] = (
    np.floor(era5_5deg["era5_lat"] / 5) * 5
)

era5_5deg["lon_chunk"] = (
    np.floor(era5_5deg["era5_lon"] / 5) * 5
)

chunks_5deg = (
    era5_5deg[
        ["lat_chunk", "lon_chunk"]
    ]
    .drop_duplicates()
    .sort_values(["lat_chunk", "lon_chunk"])
    .reset_index(drop=True)
)

print("Required ERA5 cells:", len(era5_download_list))
print("5° × 5° chunks:", len(chunks_5deg))

display(chunks_5deg.head(20))

Required ERA5 cells: 3124
5° × 5° chunks: 467

    lat_chunk  lon_chunk
0       -80.0      165.0
1       -65.0      -65.0
2       -65.0      -60.0
3       -65.0      -45.0
4       -55.0      -75.0
5       -55.0      -70.0
6       -55.0      -60.0
7       -55.0      -40.0
8       -50.0      -75.0
9       -50.0      -70.0
10      -50.0      165.0
11      -50.0      170.0
12      -45.0      -75.0
13      -45.0      -65.0
14      -45.0      145.0
15      -45.0      170.0
16      -40.0      -75.0
17      -40.0      -65.0
18      -40.0      -60.0
19      -40.0      -15.0

In [72]:
tiles_20deg = tiles.rename(
    columns={
        "lat_tile": "lat_chunk",
        "lon_tile": "lon_chunk"
    }
)

print(tiles_20deg.head())
print("\nColumns:", tiles_20deg.columns.tolist())

   lat_chunk  lon_chunk
0      -80.0      -80.0
1      -80.0      -60.0
2      -80.0      160.0
3      -60.0      -80.0
4      -60.0      -60.0

Columns: ['lat_chunk', 'lon_chunk']

In [73]:
def estimate_grid_cells(chunk_size, chunks_df):
    total = 0

    for _, chunk in chunks_df.iterrows():
        lat_points = int(chunk_size / 0.25) + 1
        lon_points = int(chunk_size / 0.25) + 1

        total += lat_points * lon_points

    return total


estimated_20deg = estimate_grid_cells(20, tiles_20deg)
estimated_10deg = estimate_grid_cells(10, chunks_10deg)
estimated_5deg = estimate_grid_cells(5, chunks_5deg)

print("Required ERA5 cells:", len(era5_download_list))

print("\nEstimated downloaded grid cells:")
print("20° × 20°:", estimated_20deg)
print("10° × 10°:", estimated_10deg)
print("5° × 5° :", estimated_5deg)

Required ERA5 cells: 3124

Estimated downloaded grid cells:
20° × 20°: 629856
10° × 10°: 366458
5° × 5° : 205947

In [74]:
def estimate_grid_cells(chunk_size, chunks_df):
    total = 0

    for _, chunk in chunks_df.iterrows():
        lat_points = int(chunk_size / 0.25) + 1
        lon_points = int(chunk_size / 0.25) + 1

        total += lat_points * lon_points

    return total


estimated_20deg = estimate_grid_cells(20, tiles_20deg)
estimated_10deg = estimate_grid_cells(10, chunks_10deg)
estimated_5deg = estimate_grid_cells(5, chunks_5deg)

print("Required ERA5 cells:", len(era5_download_list))

print("\nEstimated downloaded grid cells:")
print("20° × 20°:", estimated_20deg)
print("10° × 10°:", estimated_10deg)
print("5° × 5° :", estimated_5deg)

Required ERA5 cells: 3124

Estimated downloaded grid cells:
20° × 20°: 629856
10° × 10°: 366458
5° × 5° : 205947

In [75]:
cells_per_5deg_chunk = (
    era5_5deg
    .groupby(["lat_chunk", "lon_chunk"])
    .size()
    .reset_index(name="required_cells")
)

print("Number of 5° × 5° chunks:", len(cells_per_5deg_chunk))

print("\nRequired cells per chunk:")
print(cells_per_5deg_chunk["required_cells"].describe())

print("\nChunks with the most required cells:")
display(
    cells_per_5deg_chunk
    .sort_values("required_cells", ascending=False)
    .head(20)
)

Number of 5° × 5° chunks: 467

Required cells per chunk:
count    467.000000
mean       6.689507
std        8.597332
min        1.000000
25%        1.000000
50%        4.000000
75%        8.000000
max       63.000000
Name: required_cells, dtype: float64

Chunks with the most required cells:

     lat_chunk  lon_chunk  required_cells
403       55.0       10.0              63
352       45.0     -125.0              55
381       50.0       -5.0              48
331       40.0      -75.0              44
304       30.0      130.0              44
382       50.0        0.0              41
401       55.0       -5.0              41
402       55.0        5.0              39
338       40.0       10.0              35
329       40.0      -85.0              34
330       40.0      -80.0              32
151        0.0        5.0              32
317       35.0       20.0              32
359       45.0      -65.0              29
332       40.0      -70.0              29
396       55.0     -135.0              29
355       45.0      -85.0              28
318       35.0       25.0              27
429       60.0       20.0              27
328       40.0      -90.0              27

In [76]:
cells_per_20deg_tile = (
    era5_download_list
    .groupby(["lat_tile", "lon_tile"])
    .size()
    .reset_index(name="required_cells")
)

print("Number of 20° × 20° tiles:", len(cells_per_20deg_tile))

print("\nRequired cells per 20° tile:")
print(cells_per_20deg_tile["required_cells"].describe())

print("\nTiles with the most required cells:")
display(
    cells_per_20deg_tile
    .sort_values("required_cells", ascending=False)
    .head(20)
)

Number of 20° × 20° tiles: 96

Required cells per 20° tile:
count     96.000000
mean      32.541667
std       49.363937
min        1.000000
25%        5.000000
50%       15.000000
75%       35.500000
max      325.000000
Name: required_cells, dtype: float64

Tiles with the most required cells:

    lat_tile  lon_tile  required_cells
77      40.0       0.0             325
74      40.0     -80.0             189
76      40.0     -20.0             178
68      20.0     120.0             142
72      40.0    -140.0             125
63      20.0      20.0             123
73      40.0    -100.0             118
41       0.0     -80.0             109
78      40.0      20.0              98
90      60.0       0.0              94
50       0.0     100.0              84
58      20.0    -100.0              74
62      20.0       0.0              74
59      20.0     -80.0              70
91      60.0      20.0              69
51       0.0     120.0              68
64      20.0      40.0              59
61      20.0     -20.0              51
33     -20.0     100.0              48
45       0.0       0.0              46

In [77]:
cells_per_10deg_chunk = (
    era5_10deg
    .groupby(["lat_chunk", "lon_chunk"])
    .size()
    .reset_index(name="required_cells")
)

print("Number of 10° × 10° chunks:", len(cells_per_10deg_chunk))

print("\nRequired cells per 10° chunk:")
print(cells_per_10deg_chunk["required_cells"].describe())

print("\nChunks with the most required cells:")
display(
    cells_per_10deg_chunk
    .sort_values("required_cells", ascending=False)
    .head(20)
)

Number of 10° × 10° chunks: 218

Required cells per 10° chunk:
count    218.000000
mean      14.330275
std       21.666749
min        1.000000
25%        2.000000
50%        7.000000
75%       15.750000
max      135.000000
Name: required_cells, dtype: float64

Chunks with the most required cells:

     lat_chunk  lon_chunk  required_cells
181       50.0      -10.0             135
158       40.0      -90.0             110
183       50.0       10.0             110
182       50.0        0.0             103
159       40.0      -80.0             102
154       30.0      130.0              85
160       40.0      -70.0              80
156       40.0     -130.0              69
164       40.0       10.0              69
202       60.0       10.0              69
149       30.0       20.0              67
105       10.0      -70.0              64
148       30.0       10.0              53
203       60.0       20.0              46
87         0.0        0.0              46
175       50.0     -140.0              44
163       40.0        0.0              43
153       30.0      120.0              42
130       20.0       50.0              42
162       40.0      -10.0              42

In [78]:
cells_per_5deg_chunk = (
    era5_5deg
    .groupby(["lat_chunk", "lon_chunk"])
    .size()
    .reset_index(name="required_cells")
)

print("Number of 5° × 5° chunks:", len(cells_per_5deg_chunk))

print("\nRequired cells per 5° chunk:")
print(cells_per_5deg_chunk["required_cells"].describe())

print("\nChunks with the most required cells:")
display(
    cells_per_5deg_chunk
    .sort_values("required_cells", ascending=False)
    .head(20)
)

Number of 5° × 5° chunks: 467

Required cells per 5° chunk:
count    467.000000
mean       6.689507
std        8.597332
min        1.000000
25%        1.000000
50%        4.000000
75%        8.000000
max       63.000000
Name: required_cells, dtype: float64

Chunks with the most required cells:

     lat_chunk  lon_chunk  required_cells
403       55.0       10.0              63
352       45.0     -125.0              55
381       50.0       -5.0              48
331       40.0      -75.0              44
304       30.0      130.0              44
382       50.0        0.0              41
401       55.0       -5.0              41
402       55.0        5.0              39
338       40.0       10.0              35
329       40.0      -85.0              34
330       40.0      -80.0              32
151        0.0        5.0              32
317       35.0       20.0              32
359       45.0      -65.0              29
332       40.0      -70.0              29
396       55.0     -135.0              29
355       45.0      -85.0              28
318       35.0       25.0              27
429       60.0       20.0              27
328       40.0      -90.0              27

In [79]:
era5_10deg_download_plan = (
    era5_download_list
    .copy()
)

era5_10deg_download_plan["lat_chunk"] = (
    np.floor(era5_10deg_download_plan["era5_lat"] / 10) * 10
)

era5_10deg_download_plan["lon_chunk"] = (
    np.floor(era5_10deg_download_plan["era5_lon"] / 10) * 10
)

download_chunks = (
    era5_10deg_download_plan[
        ["lat_chunk", "lon_chunk"]
    ]
    .drop_duplicates()
    .sort_values(["lat_chunk", "lon_chunk"])
    .reset_index(drop=True)
)

print("Number of download chunks:", len(download_chunks))
print("\nFirst 10 chunks:")
display(download_chunks.head(10))

print("\nMissing values:")
print(download_chunks.isna().sum())

Number of download chunks: 218

First 10 chunks:

   lat_chunk  lon_chunk
0      -80.0      160.0
1      -70.0      -70.0
2      -70.0      -60.0
3      -70.0      -50.0
4      -60.0      -80.0
5      -60.0      -70.0
6      -60.0      -60.0
7      -60.0      -40.0
8      -50.0      -80.0
9      -50.0      -70.0

Missing values:
lat_chunk    0
lon_chunk    0
dtype: int64

In [80]:
download_chunks = (
    era5_10deg_download_plan
    .groupby(["lat_chunk", "lon_chunk"])
    .size()
    .reset_index(name="required_cells")
    .sort_values(["lat_chunk", "lon_chunk"])
    .reset_index(drop=True)
)

print("Total chunks:", len(download_chunks))
print("Total required cells:", download_chunks["required_cells"].sum())

print("\nChunk density:")
print(download_chunks["required_cells"].describe())

print("\nFirst 10 chunks:")
display(download_chunks.head(10))

print("\nDensest chunks:")
display(
    download_chunks
    .sort_values("required_cells", ascending=False)
    .head(10)
)

Total chunks: 218
Total required cells: 3124

Chunk density:
count    218.000000
mean      14.330275
std       21.666749
min        1.000000
25%        2.000000
50%        7.000000
75%       15.750000
max      135.000000
Name: required_cells, dtype: float64

First 10 chunks:

   lat_chunk  lon_chunk  required_cells
0      -80.0      160.0               1
1      -70.0      -70.0               3
2      -70.0      -60.0               1
3      -70.0      -50.0               2
4      -60.0      -80.0               8
5      -60.0      -70.0               7
6      -60.0      -60.0               1
7      -60.0      -40.0               3
8      -50.0      -80.0               4
9      -50.0      -70.0               6

Densest chunks:

     lat_chunk  lon_chunk  required_cells
181       50.0      -10.0             135
158       40.0      -90.0             110
183       50.0       10.0             110
182       50.0        0.0             103
159       40.0      -80.0             102
154       30.0      130.0              85
160       40.0      -70.0              80
156       40.0     -130.0              69
164       40.0       10.0              69
202       60.0       10.0              69