In [1]:
import os

print(os.listdir("."))

['.ipynb_checkpoints', 'ADB_port_traffic_data.csv', 'era5_multi_point_test', 'era5_multi_point_test.zip', 'era5_test', 'era5_test.zip', 'era5_test_cell_1', 'era5_test_cell_1.zip', 'era5_test_cell_2.zip', 'era5_test_cell_3.zip', 'era5_test_cell_4.zip', 'era5_test_cell_5.zip', 'global_weather_locations.csv', 'ports_master.csv', 'test_era5.py', 'Weather_Forecasting_Model.ipynb', 'WPI_2026.csv', 'WPI_Port_Data_Analysis.ipynb']

In [2]:
import pandas as pd

ports = pd.read_csv("ports_master.csv")

print("Shape:", ports.shape)
print("\nColumns:")
print(ports.columns.tolist())

print("\nFirst 5 rows:")
display(ports[[
    "Main Port Name",
    "UN/LOCODE",
    "Latitude",
    "Longitude"
]].head())

Shape: (3807, 35)

Columns:
['World Port Index Number', 'Region Name', 'Main Port Name', 'Alternate Port Name', 'UN/LOCODE', 'Country Code', 'World Water Body', 'IHO S-130 Sea Area', 'Latitude', 'Longitude', 'Tidal Range (m)', 'Entrance Width (m)', 'Channel Depth (m)', 'Anchorage Depth (m)', 'Cargo Pier Depth (m)', 'Maximum Vessel Length (m)', 'Maximum Vessel Beam (m)', 'Maximum Vessel Draft (m)', 'Harbor Size', 'Harbor Type', 'Harbor Use', 'Shelter Afforded', 'Entrance Restriction - Tide', 'Entrance Restriction - Heavy Swell', 'Entrance Restriction - Ice', 'Entrance Restriction - Other', 'Overhead Limits', 'Underkeel Clearance Management System', 'Good Holding Ground', 'Turning Area', 'Port Security', 'Traffic Separation Scheme', 'Vessel Traffic Service', 'Pilotage - Compulsory', 'Pilotage - Available']

First 5 rows:

      Main Port Name UN/LOCODE   Latitude  Longitude
0             Maurer            40.533333 -74.250000
1            Iharana           -13.350000  50.000000
2        Chake Chake            -5.250000  39.766667
3  Mjimwema Terminal            -6.816667  39.366667
4     Delta Terminal            36.850000  36.166667

In [3]:
print("Number of unique countries:", ports["Country Code"].nunique())

print("\nTop 20 countries by number of ports:")
print(
    ports["Country Code"]
    .value_counts()
    .head(20)
)

Number of unique countries: 195

Top 20 countries by number of ports:
Country Code
United States     666
Canada            285
United Kingdom    186
Japan             163
Norway            141
Italy             123
Indonesia         123
Sweden             92
Philippines        71
Denmark            69
Russia             68
Australia          66
France             66
China              66
Greece             57
India              55
Turkey             54
Spain              52
Brazil             45
Iceland            43
Name: count, dtype: int64

In [4]:
import pandas as pd

adb = pd.read_csv("ADB_port_traffic_data.csv")

adb.columns = adb.columns.str.strip()

print("ADB shape:", adb.shape)

print("\nUnique ports:")
print(adb["Port"].unique())

print("\nNumber of unique ports:", adb["Port"].nunique())

ADB shape: (3991, 70)

Unique ports:
['Antwerp' 'Busan' 'Dubai' 'Guangzhou' 'Hamburg' 'Hong Kong' 'Kaohsiung'
 'LALB' 'NYNJ' 'Ningbo' 'Port Klang' 'Qingdao' 'Rotterdam' 'Shanghai'
 'Shenzhen' 'Singapore' 'Tanjung Pelepas' 'Tianjin' 'Xiamen' nan]

Number of unique ports: 19

In [5]:
import pandas as pd

ports = pd.read_csv("ports_master.csv")

print("Total ports:", len(ports))

print("Missing latitude:", ports["Latitude"].isna().sum())
print("Missing longitude:", ports["Longitude"].isna().sum())

print("\nLatitude range:")
print(ports["Latitude"].min(), "to", ports["Latitude"].max())

print("\nLongitude range:")
print(ports["Longitude"].min(), "to", ports["Longitude"].max())

Total ports: 3807
Missing latitude: 0
Missing longitude: 0

Latitude range:
-77.84999999999998 to 78.928333333

Longitude range:
-177.366667 to 179.3675

In [6]:
# Check for duplicate coordinates
duplicate_coordinates = (
    ports.groupby(["Latitude", "Longitude"])
    .size()
    .reset_index(name="count")
)

duplicate_coordinates = duplicate_coordinates[
    duplicate_coordinates["count"] > 1
]

print("Duplicate coordinate locations:", len(duplicate_coordinates))

if len(duplicate_coordinates) > 0:
    display(duplicate_coordinates.head(20))

Duplicate coordinate locations: 11

       Latitude   Longitude  count
1578  34.700000  134.833333      2
1943  39.950000  -75.133333      2
1974  40.550000  -74.250000      2
1980  40.633333  -74.200000      2
1982  40.633333  -74.066667      2
2195  42.616667  -82.516667      2
2199  42.650000  -73.750000      2
2349  43.966667 -124.116667      2
2525  45.433333  -75.700000      2
2924  51.433333    0.700000      2
3426  59.233333 -135.433333      2

In [7]:
# Create unique weather locations from the global port database

weather_locations = (
    ports[
        [
            "World Port Index Number",
            "Main Port Name",
            "UN/LOCODE",
            "Country Code",
            "Latitude",
            "Longitude"
        ]
    ]
    .drop_duplicates(subset=["Latitude", "Longitude"])
    .reset_index(drop=True)
)

print("Total WPI ports:", len(ports))
print("Unique weather locations:", len(weather_locations))

display(weather_locations.head(10))

Total WPI ports: 3807
Unique weather locations: 3796

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude
0,7950.0,Maurer,,United States,40.533333,-74.250000
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000
7,7010.0,New Harbor,,United States,43.866667,-69.483333
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000

In [8]:
weather_locations = (
    ports[
        [
            "World Port Index Number",
            "Main Port Name",
            "UN/LOCODE",
            "Country Code",
            "Latitude",
            "Longitude"
        ]
    ]
    .drop_duplicates(subset=["Latitude", "Longitude"])
    .reset_index(drop=True)
)

print("Total WPI ports:", len(ports))
print("Unique weather locations:", len(weather_locations))

display(weather_locations.head(10))

Total WPI ports: 3807
Unique weather locations: 3796

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude
0,7950.0,Maurer,,United States,40.533333,-74.250000
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000
7,7010.0,New Harbor,,United States,43.866667,-69.483333
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000

In [9]:
# Save unique global weather locations

weather_locations.to_csv(
    "global_weather_locations.csv",
    index=False
)

print("Saved:", "global_weather_locations.csv")
print("Rows:", len(weather_locations))
print("Columns:", list(weather_locations.columns))

Saved: global_weather_locations.csv
Rows: 3796
Columns: ['World Port Index Number', 'Main Port Name', 'UN/LOCODE', 'Country Code', 'Latitude', 'Longitude']

In [10]:
# Map each port to its ERA5 atmospheric grid cell

weather_locations["era5_lat"] = (
    (weather_locations["Latitude"] * 4).round() / 4
)

weather_locations["era5_lon"] = (
    (weather_locations["Longitude"] * 4).round() / 4
)

unique_era5_cells = (
    weather_locations[
        ["era5_lat", "era5_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique weather locations:", len(weather_locations))
print("Unique ERA5 atmospheric grid cells:", len(unique_era5_cells))

display(unique_era5_cells.head(10))

Unique weather locations: 3796
Unique ERA5 atmospheric grid cells: 3124

   era5_lat  era5_lon
0     40.50    -74.25
1    -13.25     50.00
2     -5.25     39.75
3     -6.75     39.25
4     36.75     36.25
5     -5.50    106.25
6     36.25     -5.25
7     43.75    -69.50
8    -22.75    -43.25
9     28.00     35.25

In [11]:
# Map each port to the ERA5 ocean-wave grid

weather_locations["wave_lat"] = (
    (weather_locations["Latitude"] * 2).round() / 2
)

weather_locations["wave_lon"] = (
    (weather_locations["Longitude"] * 2).round() / 2
)

unique_wave_cells = (
    weather_locations[
        ["wave_lat", "wave_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique weather locations:", len(weather_locations))
print("Unique ERA5 atmospheric cells:", len(unique_era5_cells))
print("Unique ERA5 wave cells:", len(unique_wave_cells))

display(unique_wave_cells.head(10))

Unique weather locations: 3796
Unique ERA5 atmospheric cells: 3124
Unique ERA5 wave cells: 2581

   wave_lat  wave_lon
0      40.5     -74.0
1     -13.5      50.0
2      -5.0      40.0
3      -7.0      39.5
4      37.0      36.0
5      -5.5     106.0
6      36.0      -5.5
7      44.0     -69.5
8     -23.0     -43.0
9      28.0      35.0

In [12]:
print("Global weather locations:", len(weather_locations))

print(
    "Unique ERA5 atmospheric cells:",
    weather_locations[["era5_lat", "era5_lon"]]
    .drop_duplicates()
    .shape[0]
)

print(
    "Unique ERA5 wave cells:",
    weather_locations[["wave_lat", "wave_lon"]]
    .drop_duplicates()
    .shape[0]
)

weather_locations[
    [
        "Main Port Name",
        "UN/LOCODE",
        "Latitude",
        "Longitude",
        "era5_lat",
        "era5_lon",
        "wave_lat",
        "wave_lon"
    ]
].head(10)

Global weather locations: 3796
Unique ERA5 atmospheric cells: 3124
Unique ERA5 wave cells: 2581

,Main Port Name,UN/LOCODE,Latitude,Longitude,era5_lat,era5_lon,wave_lat,wave_lon
0,Maurer,,40.533333,-74.250000,40.50,-74.25,40.5,-74.0
1,Iharana,,-13.350000,50.000000,-13.25,50.00,-13.5,50.0
2,Chake Chake,,-5.250000,39.766667,-5.25,39.75,-5.0,40.0
3,Mjimwema Terminal,,-6.816667,39.366667,-6.75,39.25,-7.0,39.5
4,Delta Terminal,,36.850000,36.166667,36.75,36.25,37.0,36.0
5,Cinta Oil Terminal,,-5.500000,106.233333,-5.50,106.25,-5.5,106.0
6,Europa Point,,36.133333,-5.350000,36.25,-5.25,36.0,-5.5
7,New Harbor,,43.866667,-69.483333,43.75,-69.50,44.0,-69.5
8,Dtse / Gegua Oil Terminal,,-22.816667,-43.150000,-22.75,-43.25,-23.0,-43.0
9,Sharmah,,27.933333,35.250000,28.00,35.25,28.0,35.0

In [13]:
print("Shape:", weather_locations.shape)

print("\nColumns:")
print(weather_locations.columns.tolist())

print("\nFirst 10 locations:")
display(weather_locations.head(10))

print("\nUnique countries:", weather_locations["Country Code"].nunique())

print("\nUnique ERA5 cells:",
      weather_locations[["era5_lat", "era5_lon"]].drop_duplicates().shape[0])

print("\nUnique wave cells:",
      weather_locations[["wave_lat", "wave_lon"]].drop_duplicates().shape[0])

Shape: (3796, 10)

Columns:
['World Port Index Number', 'Main Port Name', 'UN/LOCODE', 'Country Code', 'Latitude', 'Longitude', 'era5_lat', 'era5_lon', 'wave_lat', 'wave_lon']

First 10 locations:

,World Port Index Number,Main Port Name,UN/LOCODE,Country Code,Latitude,Longitude,era5_lat,era5_lon,wave_lat,wave_lon
0,7950.0,Maurer,,United States,40.533333,-74.250000,40.50,-74.25,40.5,-74.0
1,47620.0,Iharana,,Madagascar,-13.350000,50.000000,-13.25,50.00,-13.5,50.0
2,47020.0,Chake Chake,,Tanzania,-5.250000,39.766667,-5.25,39.75,-5.0,40.0
3,47005.0,Mjimwema Terminal,,Tanzania,-6.816667,39.366667,-6.75,39.25,-7.0,39.5
4,44804.0,Delta Terminal,,Turkey,36.850000,36.166667,36.75,36.25,37.0,36.0
5,50350.0,Cinta Oil Terminal,,Indonesia,-5.500000,106.233333,-5.50,106.25,-5.5,106.0
6,38330.0,Europa Point,,Gibraltar,36.133333,-5.350000,36.25,-5.25,36.0,-5.5
7,7010.0,New Harbor,,United States,43.866667,-69.483333,43.75,-69.50,44.0,-69.5
8,12900.0,Dtse / Gegua Oil Terminal,,Brazil,-22.816667,-43.150000,-22.75,-43.25,-23.0,-43.0
9,48104.0,Sharmah,,Saudi Arabia,27.933333,35.250000,28.00,35.25,28.0,35.0

Unique countries: 195

Unique ERA5 cells: 3124

Unique wave cells: 2581

In [14]:
era5_cells = (
    weather_locations[
        ["era5_lat", "era5_lon"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("ERA5 cells:", era5_cells.shape)

display(era5_cells.head(20))

ERA5 cells: (3124, 2)

    era5_lat  era5_lon
0      40.50    -74.25
1     -13.25     50.00
2      -5.25     39.75
3      -6.75     39.25
4      36.75     36.25
5      -5.50    106.25
6      36.25     -5.25
7      43.75    -69.50
8     -22.75    -43.25
9      28.00     35.25
10     29.75    -95.25
11     44.25    -68.50
12     43.75    -69.00
13     -8.00    -14.25
14      8.00    102.25
15     -0.75    119.75
16     38.50     23.25
17     37.50     -1.50
18     37.00     15.25
19     19.50     37.25

In [15]:
test_era5_cells = era5_cells.head(5)

display(test_era5_cells)

   era5_lat  era5_lon
0     40.50    -74.25
1    -13.25     50.00
2     -5.25     39.75
3     -6.75     39.25
4     36.75     36.25

In [16]:
import cdsapi

client = cdsapi.Client()

test_cells = test_era5_cells.values.tolist()

for i, (lat, lon) in enumerate(test_cells, start=1):

    print(f"Downloading cell {i}/5: {lat}, {lon}")

    client.retrieve(
        "reanalysis-era5-single-levels",
        {
            "product_type": "reanalysis",
            "variable": [
                "10m_u_component_of_wind",
                "10m_v_component_of_wind",
                "total_precipitation",
                "2m_temperature"
            ],
            "year": "2024",
            "month": "01",
            "day": "01",
            "time": [
                "00:00",
                "06:00",
                "12:00",
                "18:00"
            ],
            "area": [
                lat + 0.125,
                lon - 0.125,
                lat - 0.125,
                lon + 0.125
            ],
            "data_format": "netcdf",
            "download_format": "unarchived"
        },
        f"era5_test_cell_{i}.zip"
    )

print("All 5 ERA5 test downloads completed.")

Downloading cell 1/5: 40.5, -74.25

2026-09-26 22:12:24,783 INFO Request ID is 52062527-afa5-46c0-9b90-1a3bafc71461
2026-09-26 22:12:25,015 INFO status has been updated to successful

73e44e53361db01b56393d0fe1712cb4.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 2/5: -13.25, 50.0

2026-09-26 22:12:30,216 INFO Request ID is 8841c67c-f547-40e9-ae9f-432ce647a2fa
2026-09-26 22:12:30,557 INFO status has been updated to successful

27fd17361bb425b5955e6ef3225ae6.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Recovering from connection error [HTTPSConnectionPool(host='object-store.os-api.cci2.ecmwf.int', port=443): Max retries exceeded with url: /cci2-prod-cache-1/2026-09-25/27fd17361bb425b5955e6ef3225ae6.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A1431C7750>, 'Connection to object-store.os-api.cci2.ecmwf.int timed out. (connect timeout=60)'))], attempt 1 of 500
Retrying in 120 seconds

27fd17361bb425b5955e6ef3225ae6.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 3/5: -5.25, 39.75

Recovering from connection error [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Read timed out. (read timeout=60)], attempt 1 of 500
Retrying in 120 seconds
2026-09-26 22:18:20,655 INFO Request ID is 01a8f8f5-a9c6-4d20-80e5-9782907d1551
2026-09-26 22:18:20,850 INFO status has been updated to successful

a038be5109b2afecc128a65aeaa4350b.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 4/5: -6.75, 39.25

2026-09-26 22:18:25,038 INFO Request ID is e0d6d171-93d4-4f24-8950-55eedf4ac23d
2026-09-26 22:18:25,233 INFO status has been updated to successful

1c96d60a1c481167f036cf71aa9c6e6a.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Downloading cell 5/5: 36.75, 36.25

2026-09-26 22:18:30,999 INFO Request ID is a0e211d5-0880-4563-a8ba-a09382cfd18e
2026-09-26 22:18:31,192 INFO status has been updated to successful

5bd7257876d460b013958bd4be24684.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Recovering from connection error [('Connection broken: IncompleteRead(64904 bytes read, 4615 more expected)', IncompleteRead(64904 bytes read, 4615 more expected))], attempt 1 of 500
Retrying in 120 seconds

5bd7257876d460b013958bd4be24684.zip: 0.00B [00:00, ?B/s]

All 5 ERA5 test downloads completed.

In [17]:
import os
import glob

files = glob.glob("era5_test_cell_*.zip")

print("Downloaded files:", len(files))

for file in files:
    size_kb = os.path.getsize(file) / 1024
    print(f"{file} → {size_kb:.2f} KB")

Downloaded files: 5
era5_test_cell_1.zip → 67.89 KB
era5_test_cell_2.zip → 67.89 KB
era5_test_cell_3.zip → 67.89 KB
era5_test_cell_4.zip → 67.89 KB
era5_test_cell_5.zip → 67.89 KB

In [18]:
import zipfile
import os

zip_file = "era5_test_cell_1.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

In [19]:
import zipfile
import xarray as xr

zip_file = "era5_test_cell_1.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall("era5_test_cell_1")

instant_file = "era5_test_cell_1/data_stream-oper_stepType-instant.nc"
accum_file = "era5_test_cell_1/data_stream-oper_stepType-accum.nc"

instant_ds = xr.open_dataset(instant_file, engine="netcdf4")
accum_ds = xr.open_dataset(accum_file, engine="netcdf4")

print("=== INSTANT DATA ===")
print(instant_ds)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds)

=== INSTANT DATA ===
<xarray.Dataset> Size: 168B
Dimensions:     (valid_time: 4, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 16B ...
    v10         (valid_time, latitude, longitude) float32 16B ...
    t2m         (valid_time, latitude, longitude) float32 16B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-25T16:45 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 136B
Dimensions:     (valid_time: 4, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 16B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-25T16:45 GRIB to CDM+CF via cfgrib-0.9.1...

In [20]:
import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00",
            "06:00",
            "12:00",
            "18:00"
        ],
        "area": [
            40.75,
            -74.50,
            40.25,
            -74.00
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_multi_point_test.zip"
)

print("Multi-point ERA5 download completed.")

2026-09-26 22:22:24,121 INFO Request ID is 6ee29677-8282-43ef-9810-b1dd310fece8
2026-09-26 22:22:24,355 INFO status has been updated to successful

8a15e5f0f0e9aa761edf76851d80ee8a.zip:   0%|          | 0.00/67.4k [00:00<?, ?B/s]

Recovering from connection error [HTTPSConnectionPool(host='object-store.os-api.cci2.ecmwf.int', port=443): Max retries exceeded with url: /cci2-prod-cache-3/2026-09-23/8a15e5f0f0e9aa761edf76851d80ee8a.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A140091950>, 'Connection to object-store.os-api.cci2.ecmwf.int timed out. (connect timeout=60)'))], attempt 1 of 500
Retrying in 120 seconds

8a15e5f0f0e9aa761edf76851d80ee8a.zip:   0%|          | 0.00/67.4k [00:00<?, ?B/s]

Multi-point ERA5 download completed.

In [21]:
import zipfile

zip_file = "era5_multi_point_test.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    print("Files inside ZIP:")
    for name in z.namelist():
        print(name)

Files inside ZIP:
data_stream-oper_stepType-instant.nc
data_stream-oper_stepType-accum.nc

In [22]:
import zipfile
import xarray as xr

zip_file = "era5_multi_point_test.zip"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall("era5_multi_point_test")

instant_file = "era5_multi_point_test/data_stream-oper_stepType-instant.nc"
accum_file = "era5_multi_point_test/data_stream-oper_stepType-accum.nc"

instant_ds = xr.open_dataset(instant_file, engine="netcdf4")
accum_ds = xr.open_dataset(accum_file, engine="netcdf4")

print("=== INSTANT DATA ===")
print(instant_ds)

print("\n=== ACCUMULATED DATA ===")
print(accum_ds)

=== INSTANT DATA ===
<xarray.Dataset> Size: 584B
Dimensions:     (valid_time: 4, latitude: 3, longitude: 3)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 24B 40.75 40.5 40.25
  * longitude   (longitude) float64 24B -74.5 -74.25 -74.0
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 144B ...
    v10         (valid_time, latitude, longitude) float32 144B ...
    t2m         (valid_time, latitude, longitude) float32 144B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.1...

=== ACCUMULATED DATA ===
<xarray.Dataset> Size: 296B
Dimensions:     (valid_time: 4, latitude: 3, longitude: 3)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2024-01-01 ... 2024-01-01T18:...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 24B 40.75 40.5 40.25
  * longitude   (longitude) float64 24B -74.5 -74.25 -74.0
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 144B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.1...

In [23]:
print("ERA5 latitude range:")
print("Minimum:", era5_cells["era5_lat"].min())
print("Maximum:", era5_cells["era5_lat"].max())

print("\nERA5 longitude range:")
print("Minimum:", era5_cells["era5_lon"].min())
print("Maximum:", era5_cells["era5_lon"].max())

print("\nTotal ERA5 cells:", len(era5_cells))

ERA5 latitude range:
Minimum: -77.75
Maximum: 79.0

ERA5 longitude range:
Minimum: -177.25
Maximum: 179.25

Total ERA5 cells: 3124

In [24]:
import numpy as np

era5_cells["lat_tile"] = (
    np.floor(era5_cells["era5_lat"] / 20) * 20
)

era5_cells["lon_tile"] = (
    np.floor(era5_cells["era5_lon"] / 20) * 20
)

tiles = (
    era5_cells[["lat_tile", "lon_tile"]]
    .drop_duplicates()
    .sort_values(["lat_tile", "lon_tile"])
    .reset_index(drop=True)
)

print("Required geographic tiles:", len(tiles))

display(tiles.head(20))

Required geographic tiles: 96

    lat_tile  lon_tile
0      -80.0     -80.0
1      -80.0     -60.0
2      -80.0     160.0
3      -60.0     -80.0
4      -60.0     -60.0
5      -60.0     -40.0
6      -60.0     140.0
7      -60.0     160.0
8      -40.0    -180.0
9      -40.0    -160.0
10     -40.0    -140.0
11     -40.0     -80.0
12     -40.0     -60.0
13     -40.0     -20.0
14     -40.0       0.0
15     -40.0      20.0
16     -40.0      40.0
17     -40.0     100.0
18     -40.0     120.0
19     -40.0     140.0

In [25]:
tile_counts = (
    era5_cells
    .groupby(["lat_tile", "lon_tile"])
    .size()
    .reset_index(name="cell_count")
    .sort_values("cell_count", ascending=False)
)

print("Total tiles:", len(tile_counts))
print("Total cells:", tile_counts["cell_count"].sum())

print("\nLargest tiles:")
display(tile_counts.head(20))

print("\nTile statistics:")
print(tile_counts["cell_count"].describe())

Total tiles: 96
Total cells: 3124

Largest tiles:

    lat_tile  lon_tile  cell_count
77      40.0       0.0         325
74      40.0     -80.0         189
76      40.0     -20.0         178
68      20.0     120.0         142
72      40.0    -140.0         125
63      20.0      20.0         123
73      40.0    -100.0         118
41       0.0     -80.0         109
78      40.0      20.0          98
90      60.0       0.0          94
50       0.0     100.0          84
58      20.0    -100.0          74
62      20.0       0.0          74
59      20.0     -80.0          70
91      60.0      20.0          69
51       0.0     120.0          68
64      20.0      40.0          59
61      20.0     -20.0          51
33     -20.0     100.0          48
45       0.0       0.0          46

Tile statistics:
count     96.000000
mean      32.541667
std       49.363937
min        1.000000
25%        5.000000
50%       15.000000
75%       35.500000
max      325.000000
Name: cell_count, dtype: float64

In [26]:
print("Instant variable units:")

for var in ["u10", "v10", "t2m"]:
    print(var, "→", instant_ds[var].attrs.get("units"))

print("\nAccumulated variable units:")

print("tp →", accum_ds["tp"].attrs.get("units"))

print("\nSample values:")

print("u10:")
print(instant_ds["u10"].values)

print("\nv10:")
print(instant_ds["v10"].values)

print("\nt2m:")
print(instant_ds["t2m"].values)

print("\ntp:")
print(accum_ds["tp"].values)

Instant variable units:
u10 → m s**-1
v10 → m s**-1
t2m → K

Accumulated variable units:
tp → m

Sample values:
u10:
[[[ 1.5779114   1.1335754   0.85232544]
  [ 1.6697083   1.3923645   2.2937317 ]
  [ 1.4831848   1.837677    2.8406067 ]]

 [[ 2.1404266   2.2576141   2.1882782 ]
  [ 1.7097626   1.9763641   3.01445   ]
  [ 1.1082001   1.6472626   2.8044891 ]]

 [[ 0.63941956  0.857193    0.9480133 ]
  [ 0.06813049  0.22731018  0.6198883 ]
  [-0.2160492   0.18922424  0.622818  ]]

 [[ 0.52511597  0.46847534  0.5729675 ]
  [ 0.2585144   0.24581909  0.03585815]
  [ 0.27609253  0.12667847 -0.11941528]]]

v10:
[[[ 1.114914    1.130539    1.099289  ]
  [ 1.2692108   1.271164    0.65104675]
  [ 0.8326874   0.686203    0.05241394]]

 [[ 0.4647522   0.69229126  0.9315491 ]
  [ 0.62197876  0.8729553   1.26651   ]
  [ 0.9911194   1.1825256   1.6034241 ]]

 [[-0.71847534 -0.4958191  -0.09347534]
  [-1.01828    -0.8366394  -0.98605347]
  [-1.0104675  -1.071991   -1.2380066 ]]

 [[-1.6524353  -1.4502869  -1.1778259 ]
  [-1.2705994  -1.0870056  -1.0000916 ]
  [-0.99227905 -0.7930603  -0.72958374]]]

t2m:
[[[277.47412 278.01514 278.67334]
  [278.07178 278.63232 279.20068]
  [278.05615 278.47607 279.10693]]

 [[276.74695 277.33093 277.90125]
  [277.26648 277.8114  278.30164]
  [277.0946  277.53015 278.0536 ]]

 [[276.26553 276.70694 277.26944]
  [276.57217 277.10733 277.7499 ]
  [276.1913  277.0624  277.78897]]

 [[280.18326 279.82974 279.5309 ]
  [280.36295 279.6852  279.22232]
  [280.31216 280.3024  279.7184 ]]]

tp:
[[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [9.5367432e-07 4.7683716e-06 4.7683716e-06]]

 [[1.5401840e-04 1.9168854e-04 1.4305115e-04]
  [7.5340271e-05 1.1253357e-04 1.3971329e-04]
  [2.7656555e-05 7.9631805e-05 9.9658966e-05]]

 [[1.9073486e-06 1.4305115e-06 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]]

 [[3.3378601e-06 1.9073486e-06 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [9.5367432e-07 9.5367432e-07 9.5367432e-07]]]

In [27]:
print("=== PRECIPITATION ATTRIBUTES ===")
print(accum_ds["tp"].attrs)

print("\n=== PRECIPITATION ENCODING ===")
print(accum_ds["tp"].encoding)

print("\n=== DATASET ATTRIBUTES ===")
print(accum_ds.attrs)

=== PRECIPITATION ATTRIBUTES ===
{'GRIB_paramId': np.int64(228), 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': np.int64(9), 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': np.int64(1), 'GRIB_stepType': 'accum', 'GRIB_gridType': 'regular_ll', 'GRIB_uvRelativeToGrid': np.int64(0), 'GRIB_NV': np.int64(0), 'GRIB_Nx': np.int64(3), 'GRIB_Ny': np.int64(3), 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'tp', 'GRIB_gridDefinitionDescription': 'Latitude/Longitude Grid', 'GRIB_iDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_iScansNegatively': np.int64(0), 'GRIB_jDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_jPointsAreConsecutive': np.int64(0), 'GRIB_jScansPositively': np.int64(0), 'GRIB_latitudeOfFirstGridPointInDegrees': np.float64(40.75), 'GRIB_latitudeOfLastGridPointInDegrees': np.float64(40.25), 'GRIB_longitudeOfFirstGridPointInDegrees': np.float64(-74.5), 'GRIB_longitudeOfLastGridPointInDegrees': np.float64(-74.0), 'GRIB_missingValue': np.float64(3.4028234663852886e+38), 'GRIB_name': 'Total precipitation', 'GRIB_shortName': 'tp', 'GRIB_totalNumber': np.int64(0), 'GRIB_units': 'm', 'long_name': 'Total precipitation', 'units': 'm', 'standard_name': 'unknown', 'GRIB_surface': np.float64(0.0)}

=== PRECIPITATION ENCODING ===
{'dtype': dtype('float32'), 'zlib': True, 'szip': False, 'zstd': False, 'bzip2': False, 'blosc': False, 'shuffle': True, 'complevel': 1, 'fletcher32': False, 'contiguous': False, 'chunksizes': (4, 3, 3), 'preferred_chunks': {'valid_time': 4, 'latitude': 3, 'longitude': 3}, 'source': 'C:\\Users\\KIIT\\OneDrive\\Desktop\\MarineGuard-AI\\ml\\era5_multi_point_test\\data_stream-oper_stepType-accum.nc', 'original_shape': (4, 3, 3), '_FillValue': np.float32(nan), 'coordinates': 'number valid_time latitude longitude expver'}

=== DATASET ATTRIBUTES ===
{'GRIB_centre': 'ecmf', 'GRIB_centreDescription': 'European Centre for Medium-Range Weather Forecasts', 'GRIB_subCentre': np.int64(0), 'Conventions': 'CF-1.7', 'institution': 'European Centre for Medium-Range Weather Forecasts', 'history': '2026-09-23T17:59 GRIB to CDM+CF via cfgrib-0.9.15.1/ecCodes-2.48.2 with {"source": "tmphqmw6711/data.grib", "filter_by_keys": {"stream": ["oper"], "stepType": ["accum"]}, "encode_cf": ["parameter", "time", "geography", "vertical"]}'}

In [28]:
print("=== TIME COORDINATES ===")
print(accum_ds["valid_time"].values)

print("\n=== STEP INFORMATION ===")

for key in accum_ds.coords:
    print(key, "→", accum_ds.coords[key].values)

print("\n=== TP ATTRIBUTES ===")
print(accum_ds["tp"].attrs)

=== TIME COORDINATES ===
['2024-01-01T00:00:00.000000000' '2024-01-01T06:00:00.000000000'
 '2024-01-01T12:00:00.000000000' '2024-01-01T18:00:00.000000000']

=== STEP INFORMATION ===
number → 0
valid_time → ['2024-01-01T00:00:00.000000000' '2024-01-01T06:00:00.000000000'
 '2024-01-01T12:00:00.000000000' '2024-01-01T18:00:00.000000000']
latitude → [40.75 40.5  40.25]
longitude → [-74.5  -74.25 -74.  ]
expver → ['0001' '0001' '0001' '0001']

=== TP ATTRIBUTES ===
{'GRIB_paramId': np.int64(228), 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': np.int64(9), 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': np.int64(1), 'GRIB_stepType': 'accum', 'GRIB_gridType': 'regular_ll', 'GRIB_uvRelativeToGrid': np.int64(0), 'GRIB_NV': np.int64(0), 'GRIB_Nx': np.int64(3), 'GRIB_Ny': np.int64(3), 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'tp', 'GRIB_gridDefinitionDescription': 'Latitude/Longitude Grid', 'GRIB_iDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_iScansNegatively': np.int64(0), 'GRIB_jDirectionIncrementInDegrees': np.float64(0.25), 'GRIB_jPointsAreConsecutive': np.int64(0), 'GRIB_jScansPositively': np.int64(0), 'GRIB_latitudeOfFirstGridPointInDegrees': np.float64(40.75), 'GRIB_latitudeOfLastGridPointInDegrees': np.float64(40.25), 'GRIB_longitudeOfFirstGridPointInDegrees': np.float64(-74.5), 'GRIB_longitudeOfLastGridPointInDegrees': np.float64(-74.0), 'GRIB_missingValue': np.float64(3.4028234663852886e+38), 'GRIB_name': 'Total precipitation', 'GRIB_shortName': 'tp', 'GRIB_totalNumber': np.int64(0), 'GRIB_units': 'm', 'long_name': 'Total precipitation', 'units': 'm', 'standard_name': 'unknown', 'GRIB_surface': np.float64(0.0)}

In [29]:
import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind",
            "total_precipitation",
            "2m_temperature"
        ],
        "year": "2024",
        "month": "01",
        "day": "01",
        "time": [
            "00:00",
            "01:00",
            "02:00",
            "03:00",
            "04:00",
            "05:00",
            "06:00",
            "07:00",
            "08:00",
            "09:00",
            "10:00",
            "11:00",
            "12:00",
            "13:00",
            "14:00",
            "15:00",
            "16:00",
            "17:00",
            "18:00",
            "19:00",
            "20:00",
            "21:00",
            "22:00",
            "23:00"
        ],
        "area": [
            40.625,
            -74.375,
            40.375,
            -74.125
        ],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_hourly_test.zip"
)

print("Hourly ERA5 test download completed.")

2026-09-26 22:52:17,415 INFO Request ID is caf806b5-bf3d-4a05-817f-05ca02bd5a55
2026-09-26 22:52:17,970 INFO status has been updated to accepted
2026-09-26 22:52:53,396 INFO status has been updated to running
2026-09-26 22:53:10,772 INFO status has been updated to successful

569a8a12c644bd9aebd86cad04f57d5.zip:   0%|          | 0.00/67.9k [00:00<?, ?B/s]

Hourly ERA5 test download completed.

In [30]:
import zipfile

with zipfile.ZipFile("era5_hourly_test.zip", "r") as z:
    print(z.namelist())
    z.extractall("era5_hourly_test")

['data_stream-oper_stepType-instant.nc', 'data_stream-oper_stepType-accum.nc']

In [31]:
import xarray as xr

accum_hourly = xr.open_dataset(
    "era5_hourly_test/data_stream-oper_stepType-accum.nc",
    engine="netcdf4"
)

print(accum_hourly)

<xarray.Dataset> Size: 696B
Dimensions:     (valid_time: 24, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 96B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-26T17:22 GRIB to CDM+CF via cfgrib-0.9.1...

In [32]:
print("=== HOURLY PRECIPITATION ===")

for time, value in zip(
    accum_hourly["valid_time"].values,
    accum_hourly["tp"].values[:, 0, 0]
):
    print(time, "→", value, "m")

=== HOURLY PRECIPITATION ===
2024-01-01T00:00:00.000000000 → 0.0 m
2024-01-01T01:00:00.000000000 → 0.0 m
2024-01-01T02:00:00.000000000 → 4.5776367e-05 m
2024-01-01T03:00:00.000000000 → 5.2452087e-06 m
2024-01-01T04:00:00.000000000 → 3.862381e-05 m
2024-01-01T05:00:00.000000000 → 0.00015974045 m
2024-01-01T06:00:00.000000000 → 0.00011253357 m
2024-01-01T07:00:00.000000000 → 0.0 m
2024-01-01T08:00:00.000000000 → 0.0 m
2024-01-01T09:00:00.000000000 → 0.0 m
2024-01-01T10:00:00.000000000 → 0.0 m
2024-01-01T11:00:00.000000000 → 0.0 m
2024-01-01T12:00:00.000000000 → 0.0 m
2024-01-01T13:00:00.000000000 → 0.0 m
2024-01-01T14:00:00.000000000 → 0.0 m
2024-01-01T15:00:00.000000000 → 0.0 m
2024-01-01T16:00:00.000000000 → 0.0 m
2024-01-01T17:00:00.000000000 → 0.0 m
2024-01-01T18:00:00.000000000 → 0.0 m
2024-01-01T19:00:00.000000000 → 8.583069e-06 m
2024-01-01T20:00:00.000000000 → 4.7683716e-07 m
2024-01-01T21:00:00.000000000 → 0.0 m
2024-01-01T22:00:00.000000000 → 0.0 m
2024-01-01T23:00:00.000000000 → 0.0 m

In [33]:
import pandas as pd
import numpy as np

weather_test = pd.DataFrame({
    "valid_time": accum_hourly["valid_time"].values,
    "latitude": accum_hourly["latitude"].values[0],
    "longitude": accum_hourly["longitude"].values[0],
    "precipitation_m": accum_hourly["tp"].values[:, 0, 0]
})

weather_test["precipitation_mm"] = (
    weather_test["precipitation_m"] * 1000
)

weather_test.head(10)

           valid_time  latitude  longitude  precipitation_m  precipitation_mm
0 2024-01-01 00:00:00      40.5     -74.25         0.000000          0.000000
1 2024-01-01 01:00:00      40.5     -74.25         0.000000          0.000000
2 2024-01-01 02:00:00      40.5     -74.25         0.000046          0.045776
3 2024-01-01 03:00:00      40.5     -74.25         0.000005          0.005245
4 2024-01-01 04:00:00      40.5     -74.25         0.000039          0.038624
5 2024-01-01 05:00:00      40.5     -74.25         0.000160          0.159740
6 2024-01-01 06:00:00      40.5     -74.25         0.000113          0.112534
7 2024-01-01 07:00:00      40.5     -74.25         0.000000          0.000000
8 2024-01-01 08:00:00      40.5     -74.25         0.000000          0.000000
9 2024-01-01 09:00:00      40.5     -74.25         0.000000          0.000000

In [34]:
instant_hourly = xr.open_dataset(
    "era5_hourly_test/data_stream-oper_stepType-instant.nc",
    engine="netcdf4"
)

print(instant_hourly)

<xarray.Dataset> Size: 888B
Dimensions:     (valid_time: 24, latitude: 1, longitude: 1)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23...
    expver      (valid_time) <U4 384B ...
  * latitude    (latitude) float64 8B 40.5
  * longitude   (longitude) float64 8B -74.25
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 96B ...
    v10         (valid_time, latitude, longitude) float32 96B ...
    t2m         (valid_time, latitude, longitude) float32 96B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-26T17:22 GRIB to CDM+CF via cfgrib-0.9.1...

In [35]:
weather_test = pd.DataFrame({
    "valid_time": instant_hourly["valid_time"].values,
    "latitude": instant_hourly["latitude"].values[0],
    "longitude": instant_hourly["longitude"].values[0],

    "u10": instant_hourly["u10"].values[:, 0, 0],
    "v10": instant_hourly["v10"].values[:, 0, 0],
    "temperature_k": instant_hourly["t2m"].values[:, 0, 0],

    "precipitation_m": accum_hourly["tp"].values[:, 0, 0]
})

weather_test.head()

,valid_time,latitude,longitude,u10,v10,temperature_k,precipitation_m
0,2024-01-01 00:00:00,40.5,-74.25,1.392365,1.271164,278.632080,0.000000
1,2024-01-01 01:00:00,40.5,-74.25,1.411575,1.185440,278.464844,0.000000
2,2024-01-01 02:00:00,40.5,-74.25,1.194931,1.098785,277.939941,0.000046
3,2024-01-01 03:00:00,40.5,-74.25,1.514572,1.217392,277.829346,0.000005
4,2024-01-01 04:00:00,40.5,-74.25,1.669922,1.202515,277.924805,0.000039

In [37]:
weather_test["wind_speed_ms"] = np.sqrt(
    weather_test["u10"]**2 +
    weather_test["v10"]**2
)

weather_test["temperature_c"] = (
    weather_test["temperature_k"] - 273.15
)

weather_test["precipitation_mm"] = (
    weather_test["precipitation_m"] * 1000
)

In [38]:
weather_test[
    [
        "valid_time",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].head(10)

           valid_time  wind_speed_ms  temperature_c  precipitation_mm
0 2024-01-01 00:00:00       1.885348       5.482086          0.000000
1 2024-01-01 01:00:00       1.843316       5.314850          0.000000
2 2024-01-01 02:00:00       1.623327       4.789948          0.045776
3 2024-01-01 03:00:00       1.943186       4.679352          0.005245
4 2024-01-01 04:00:00       2.057834       4.774811          0.038624
5 2024-01-01 05:00:00       2.405361       5.082428          0.159740
6 2024-01-01 06:00:00       2.160571       4.661285          0.112534
7 2024-01-01 07:00:00       1.818360       4.855377          0.000000
8 2024-01-01 08:00:00       1.352087       4.596344          0.000000
9 2024-01-01 09:00:00       1.142918       4.827545          0.000000

In [39]:
print("Rows:", len(weather_test))

print("\nMissing values:")
print(weather_test[
    [
        "valid_time",
        "latitude",
        "longitude",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].isna().sum())

print("\nRanges:")
print("Wind speed:", weather_test["wind_speed_ms"].min(),
      "to", weather_test["wind_speed_ms"].max(), "m/s")

print("Temperature:", weather_test["temperature_c"].min(),
      "to", weather_test["temperature_c"].max(), "°C")

print("Precipitation:", weather_test["precipitation_mm"].min(),
      "to", weather_test["precipitation_mm"].max(), "mm")

Rows: 24

Missing values:
valid_time          0
latitude            0
longitude           0
wind_speed_ms       0
temperature_c       0
precipitation_mm    0
dtype: int64

Ranges:
Wind speed: 0.500170111656189 to 2.4053609371185303 m/s
Temperature: 3.276031494140625 to 6.535064697265625 °C
Precipitation: 0.0 to 0.15974044799804688 mm

In [40]:
weather_clean = weather_test[
    [
        "valid_time",
        "latitude",
        "longitude",
        "wind_speed_ms",
        "temperature_c",
        "precipitation_mm"
    ]
].copy()

weather_clean.head(10)

,valid_time,latitude,longitude,wind_speed_ms,temperature_c,precipitation_mm
0,2024-01-01 00:00:00,40.5,-74.25,1.885348,5.482086,0.000000
1,2024-01-01 01:00:00,40.5,-74.25,1.843316,5.314850,0.000000
2,2024-01-01 02:00:00,40.5,-74.25,1.623327,4.789948,0.045776
3,2024-01-01 03:00:00,40.5,-74.25,1.943186,4.679352,0.005245
4,2024-01-01 04:00:00,40.5,-74.25,2.057834,4.774811,0.038624
5,2024-01-01 05:00:00,40.5,-74.25,2.405361,5.082428,0.159740
6,2024-01-01 06:00:00,40.5,-74.25,2.160571,4.661285,0.112534
7,2024-01-01 07:00:00,40.5,-74.25,1.818360,4.855377,0.000000
8,2024-01-01 08:00:00,40.5,-74.25,1.352087,4.596344,0.000000
9,2024-01-01 09:00:00,40.5,-74.25,1.142918,4.827545,0.000000